import Foundation
import Observation

/// Controls transcript retention when generation fails or is cancelled.
public struct TranscriptErrorHandlingPolicy: Sendable, Equatable {
    private let shouldRevert: Bool

    /// Retain the prompt and the latest cumulative streaming checkpoint.
    /// Nonstreaming failures have no checkpoint and retain only the prompt.
    public static let preserveTranscript = Self(shouldRevert: false)
    /// Remove entries added by the failing request, preserving other requests.
    /// Tool side effects are not undone.
    public static let revertTranscript = Self(shouldRevert: true)
}

@Observable
public final class LanguageModelSession: @unchecked Sendable {
    public var isResponding: Bool {
        access(keyPath: \.isResponding)
        return state.withLock { $0.isResponding }
    }

    /// On failure, `nil` retains the prompt without committing streaming checkpoints.
    /// Streaming cancellation never commits the partial answer as a completed response, regardless
    /// of this policy. These defaults do not claim Foundation Models behavioral parity.
    public var transcriptErrorHandlingPolicy: TranscriptErrorHandlingPolicy? {
        get {
            access(keyPath: \.transcriptErrorHandlingPolicy)
            return state.withLock { $0.transcriptErrorHandlingPolicy }
        }
        set {
            withMutation(keyPath: \.transcriptErrorHandlingPolicy) {
                state.withLock { $0.transcriptErrorHandlingPolicy = newValue }
            }
        }
    }

    public var transcript: Transcript {
        access(keyPath: \.transcript)
        return state.withLock { $0.transcript }
    }

    /// The accumulated token usage across responses generated by this session.
    ///
    /// Counts increase as responses and streaming snapshots report usage.
    /// Restoring a transcript does not restore usage from previous sessions.
    public var usage: Usage {
        access(keyPath: \.usage)
        return state.withLock { $0.usage }
    }

    @ObservationIgnored private let state: Locked<State>

    @ObservationIgnored private let responseRelays = Locked<[UUID: Task<Void, Never>]>([:])

    /// Waits for transcript cleanup of all streaming relays registered when this call begins.
    /// Relays started later are excluded. Cancelling this wait does not cancel generation.
    /// Call after cancelling consumers and before persisting the transcript. This is an
    /// AnyLanguageModel extension; nonstreaming operations must be awaited separately.
    /// Do not call from a tool executing within one of the included responses.
    nonisolated public func waitForResponseCompletion() async {
        let tasks = responseRelays.withLock { Array($0.values) }
        for task in tasks { await task.value }
    }

    private let model: any LanguageModel
    public let tools: [any Tool]
    public let instructions: Instructions?

    /// A delegate that observes and controls tool execution.
    ///
    /// Set this property to intercept tool calls, provide custom output,
    /// or stop after tool calls are generated.
    ///
    /// - Note: This property is exclusive to AnyLanguageModel
    ///   and using it means your code is no longer drop-in compatible
    ///   with the Foundation Models framework.
    @ObservationIgnored public var toolExecutionDelegate: (any ToolExecutionDelegate)?

    public convenience init(
        model: any LanguageModel,
        tools: [any Tool] = [],
        @InstructionsBuilder instructions: () throws -> Instructions
    ) rethrows {
        try self.init(model: model, tools: tools, instructions: instructions())
    }

    public convenience init(
        model: any LanguageModel,
        tools: [any Tool] = [],
        instructions: String
    ) {
        self.init(model: model, tools: tools, instructions: Instructions(instructions), transcript: Transcript())
    }

    public convenience init(
        model: any LanguageModel,
        tools: [any Tool] = [],
        instructions: Instructions? = nil
    ) {
        self.init(model: model, tools: tools, instructions: instructions, transcript: Transcript())
    }

    public convenience init(
        model: any LanguageModel,
        tools: [any Tool] = [],
        transcript: Transcript
    ) {
        self.init(model: model, tools: tools, instructions: nil, transcript: transcript)
    }

    private init(
        model: any LanguageModel,
        tools: [any Tool],
        instructions: Instructions?,
        transcript: Transcript
    ) {
        self.model = model
        self.tools = tools
        let resolvedInstructions = instructions ?? Self.instructions(from: transcript)
        self.instructions = resolvedInstructions

        // Build transcript with instructions if provided and not already in transcript
        var finalTranscript = transcript
        if let instructions = resolvedInstructions {
            // Only add instructions if transcript doesn't already start with instructions
            let hasInstructions =
                finalTranscript.first.map { entry in
                    if case .instructions = entry { return true } else { return false }
                } ?? false

            if !hasInstructions {
                let instructionsEntry = Transcript.Entry.instructions(
                    Transcript.Instructions(
                        segments: [.text(.init(content: instructions.description))],
                        toolDefinitions:
                            tools
                            .filter(\.includesSchemaInInstructions)
                            .map { Transcript.ToolDefinition(tool: $0) }
                    )
                )
                finalTranscript.append(instructionsEntry)
            }
        }

        self.state = .init(.init(finalTranscript))
    }

    private static func instructions(from transcript: Transcript) -> Instructions? {
        guard case .instructions(let instructions)? = transcript.first else { return nil }
        guard instructions.segments.count == 1,
            case .text(let text) = instructions.segments[0]
        else {
            return nil
        }
        return Instructions(content: text.content)
    }

    public func prewarm(promptPrefix: Prompt? = nil) {
        model.prewarm(for: self, promptPrefix: promptPrefix)
    }

    nonisolated private func recordUsage(_ usage: Usage) {
        guard usage != .zero else { return }
        withMutation(keyPath: \.usage) {
            state.withLock { $0.usage.add(usage) }
        }
    }

    nonisolated private func beginResponding() {
        withMutation(keyPath: \.isResponding) {
            state.withLock { $0.beginResponding() }
        }
    }

    nonisolated private func endResponding() {
        withMutation(keyPath: \.isResponding) {
            state.withLock { $0.endResponding() }
        }
    }

    // The prompt is the only entry committed before a request succeeds. Checkpoints and
    // the final response commit atomically at completion, so rollback owns only this ID.
    nonisolated private func removePrompt(id: String) {
        withMutation(keyPath: \.transcript) {
            state.withLock { state in
                state.transcript = Transcript(entries: state.transcript.filter { $0.id != id })
            }
        }
    }

    nonisolated private func wrapRespond<T>(_ operation: (String) async throws -> T) async throws -> T {
        let promptID = UUID().uuidString
        beginResponding()
        do {
            let result = try await operation(promptID)
            endResponding()
            return result
        } catch {
            if transcriptErrorHandlingPolicy == .revertTranscript {
                removePrompt(id: promptID)
            }
            endResponding()
            throw error
        }
    }

    nonisolated private func wrapStream<Content>(
        _ upstream: sending ResponseStream<Content>,
        promptEntry: Transcript.Entry
    ) -> ResponseStream<Content> where Content: Generable, Content.PartiallyGenerated: Sendable {
        let session = self
        let relay = AsyncThrowingStream<ResponseStream<Content>.Snapshot, any Error> { continuation in
            let stream = upstream
            let relayID = UUID()
            // Publish the task under the same lock used by completion removal, so a
            // fast relay cannot finish before registration and leave a stale handle.
            let task = session.responseRelays.withLock { relays in
                let task = Task {
                    defer { session.responseRelays.withLock { _ = $0.removeValue(forKey: relayID) } }
                    session.beginResponding()
                    var lastSnapshot: ResponseStream<Content>.Snapshot?
                    var accountedUsage = Usage.zero
                    do {
                        for try await snapshot in stream {
                            lastSnapshot = snapshot
                            session.recordUsage(snapshot.usage.increment(since: &accountedUsage))
                            continuation.yield(snapshot)
                        }

                        // AsyncThrowingStream may end normally when its task is cancelled.
                        // A partial snapshot must not become a completed transcript response.
                        try Task.checkCancellation()

                        // Commit the response to the transcript
                        // before the stream reports completion,
                        // so a caller that drains the stream
                        // and starts the next turn sees the full history.
                        if let lastSnapshot {
                            // Extract text content from the generated content
                            let textContent: String
                            if case .string(let str) = lastSnapshot.rawContent.kind {
                                textContent = str
                            } else {
                                textContent = lastSnapshot.rawContent.jsonString
                            }

                            let responseEntry = Transcript.Entry.response(
                                Transcript.Response(
                                    assetIDs: [],
                                    segments: [.text(.init(content: textContent))],
                                    providerMetadata: lastSnapshot.providerMetadata
                                )
                            )
                            session.withMutation(keyPath: \.transcript) {
                                session.state.withLock {
                                    $0.transcript.append(contentsOf: lastSnapshot.transcriptEntries)
                                    $0.transcript.append(responseEntry)
                                }
                            }
                        }
                        session.endResponding()
                        continuation.finish()
                    } catch {
                        session.withMutation(keyPath: \.transcript) {
                            session.state.withLock { state in
                                if state.transcriptErrorHandlingPolicy == .preserveTranscript {
                                    state.transcript.append(contentsOf: lastSnapshot?.transcriptEntries ?? [])
                                } else if state.transcriptErrorHandlingPolicy == .revertTranscript {
                                    state.transcript = Transcript(
                                        entries: state.transcript.filter { $0.id != promptEntry.id }
                                    )
                                }
                            }
                        }
                        session.endResponding()
                        continuation.finish(throwing: error)
                    }
                }
                relays[relayID] = task
                return task
            }
            continuation.onTermination = { termination in
                if case .cancelled = termination {
                    task.cancel()
                }
            }
        }
        return ResponseStream(stream: relay)
    }

    /// Token usage reported by the model for a response.
    ///
    /// Matches the token-usage API in Foundation Models 27.
    /// Counts default to zero when the provider does not report them.
    /// Usage is cumulative across the response's tool rounds.
    public struct Usage: Sendable, Equatable, Codable {
        /// Token counts for the input submitted to the model.
        public struct Input: Sendable, Equatable, Codable {
            /// The number of input tokens reported by the provider.
            public var totalTokenCount: Int

            /// The number of input tokens read from the provider's cache.
            public var cachedTokenCount: Int

            /// Creates input token counts.
            ///
            /// - Parameters:
            ///   - totalTokenCount: The reported input token count.
            ///   - cachedTokenCount: The reported count of input tokens read from cache.
            public init(totalTokenCount: Int, cachedTokenCount: Int) {
                self.totalTokenCount = totalTokenCount
                self.cachedTokenCount = cachedTokenCount
            }
        }

        /// Token counts for the output produced by the model.
        public struct Output: Sendable, Equatable, Codable {
            /// The number of output tokens reported by the provider.
            public var totalTokenCount: Int

            /// The number of reasoning tokens reported by the provider.
            public var reasoningTokenCount: Int

            /// Creates output token counts.
            ///
            /// - Parameters:
            ///   - totalTokenCount: The reported output token count.
            ///   - reasoningTokenCount: The reported reasoning token count.
            public init(totalTokenCount: Int, reasoningTokenCount: Int) {
                self.totalTokenCount = totalTokenCount
                self.reasoningTokenCount = reasoningTokenCount
            }
        }

        /// The token counts reported for the model's input.
        public var input: Input

        /// The token counts reported for the model's output.
        public var output: Output

        /// Additional usage statistics supplied by the model.
        public var metadata: [String: GeneratedContent]

        /// The sum of the input and output token counts.
        public var totalTokenCount: Int {
            input.totalTokenCount + output.totalTokenCount
        }

        /// Creates usage from input and output token counts.
        ///
        /// - Parameters:
        ///   - input: The input token counts.
        ///   - output: The output token counts.
        ///   - metadata: Additional usage statistics,
        ///     converted to generated content for storage.
        public init(
            input: Input,
            output: Output,
            metadata: [String: any ConvertibleToGeneratedContent] = [:]
        ) {
            self.input = input
            self.output = output
            self.metadata = metadata.mapValues { $0.generatedContent }
        }

        static let zero = Self(
            input: .init(totalTokenCount: 0, cachedTokenCount: 0),
            output: .init(totalTokenCount: 0, reasoningTokenCount: 0)
        )

        /// Accumulates counts across responses;
        /// the latest value wins for each metadata key.
        mutating func add(_ other: Self) {
            input.totalTokenCount += other.input.totalTokenCount
            input.cachedTokenCount += other.input.cachedTokenCount
            output.totalTokenCount += other.output.totalTokenCount
            output.reasoningTokenCount += other.output.reasoningTokenCount
            metadata.merge(other.metadata) { _, latest in latest }
        }

        /// Returns counts not yet accounted for in this stream,
        /// retaining the highest reported count for each field
        /// and returning only new or changed metadata keys.
        func increment(since previous: inout Self) -> Self {
            func increase(_ count: Int, _ highest: inout Int) -> Int {
                let delta = max(0, count - highest)
                highest = max(highest, count)
                return delta
            }
            let changedMetadata = metadata.filter { previous.metadata[$0.key] != $0.value }
            previous.metadata.merge(changedMetadata) { _, latest in latest }
            return Self(
                input: .init(
                    totalTokenCount: increase(input.totalTokenCount, &previous.input.totalTokenCount),
                    cachedTokenCount: increase(input.cachedTokenCount, &previous.input.cachedTokenCount)
                ),
                output: .init(
                    totalTokenCount: increase(output.totalTokenCount, &previous.output.totalTokenCount),
                    reasoningTokenCount: increase(output.reasoningTokenCount, &previous.output.reasoningTokenCount)
                ),
                metadata: changedMetadata
            )
        }
    }

    /// A model response containing generated content and associated metadata.
    public struct Response<Content>: Sendable where Content: Generable, Content: Sendable {
        /// The decoded response content.
        public let content: Content

        /// The raw content produced by the model.
        public let rawContent: GeneratedContent

        /// The transcript entries associated with the response.
        public let transcriptEntries: ArraySlice<Transcript.Entry>

        /// Provider-reported token usage,
        /// with zero counts for values the provider does not report.
        public let usage: Usage

        internal let providerMetadata: [String: String]?

        /// Creates a response value from generated content and transcript entries.
        /// - Parameters:
        ///   - content: The decoded response content.
        ///   - rawContent: The raw content produced by the model.
        ///   - transcriptEntries: Transcript entries associated with the response.
        ///   - usage: Provider-reported token usage.
        public init(
            content: Content,
            rawContent: GeneratedContent,
            transcriptEntries: ArraySlice<Transcript.Entry>,
            usage: Usage = .init(
                input: .init(totalTokenCount: 0, cachedTokenCount: 0),
                output: .init(totalTokenCount: 0, reasoningTokenCount: 0)
            )
        ) {
            self.init(
                content: content,
                rawContent: rawContent,
                transcriptEntries: transcriptEntries,
                usage: usage,
                providerMetadata: nil
            )
        }

        internal init(
            content: Content,
            rawContent: GeneratedContent,
            transcriptEntries: ArraySlice<Transcript.Entry>,
            usage: Usage = .init(
                input: .init(totalTokenCount: 0, cachedTokenCount: 0),
                output: .init(totalTokenCount: 0, reasoningTokenCount: 0)
            ),
            providerMetadata: [String: String]?
        ) {
            self.content = content
            self.rawContent = rawContent
            self.transcriptEntries = transcriptEntries
            self.usage = usage
            self.providerMetadata = providerMetadata
        }
    }

    @discardableResult
    nonisolated public func respond<Content>(
        to prompt: Prompt,
        generating type: Content.Type = Content.self,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) async throws -> Response<Content> where Content: Generable {
        try await respond(
            to: prompt,
            responseFormat: type == String.self ? nil : .init(type: type),
            options: options
        ) {
            try await model.respond(
                within: self,
                to: prompt,
                generating: type,
                includeSchemaInPrompt: includeSchemaInPrompt,
                options: options
            )
        }
    }

    nonisolated private func respond<Content: Generable>(
        to prompt: Prompt,
        responseFormat: Transcript.ResponseFormat?,
        options: GenerationOptions,
        generate: () async throws -> Response<Content>
    ) async throws -> Response<Content> {
        try await wrapRespond { promptID in
            // Add prompt to transcript
            let promptEntry = Transcript.Entry.prompt(
                Transcript.Prompt(
                    id: promptID,
                    segments: [.text(.init(content: prompt.description))],
                    options: options,
                    responseFormat: responseFormat
                )
            )
            withMutation(keyPath: \.transcript) {
                state.withLock { $0.transcript.append(promptEntry) }
            }

            let response = try await generate()

            recordUsage(response.usage)

            // Add response entry to transcript
            let textContent: String
            if case .string(let str) = response.rawContent.kind {
                textContent = str
            } else {
                textContent = response.rawContent.jsonString
            }

            let responseEntry = Transcript.Entry.response(
                Transcript.Response(
                    assetIDs: [],
                    segments: [.text(.init(content: textContent))],
                    providerMetadata: response.providerMetadata
                )
            )

            // Add tool entries and response to transcript
            withMutation(keyPath: \.transcript) {
                state.withLock { lockedState in
                    lockedState.transcript.append(contentsOf: response.transcriptEntries)
                    lockedState.transcript.append(responseEntry)
                }
            }

            return response
        }
    }

    nonisolated public func streamResponse<Content>(
        to prompt: Prompt,
        generating type: Content.Type = Content.self,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) -> sending ResponseStream<Content> where Content: Generable {
        // Add prompt to transcript
        let promptEntry = Transcript.Entry.prompt(
            Transcript.Prompt(
                segments: [.text(.init(content: prompt.description))],
                options: options,
                responseFormat: type == String.self ? nil : .init(type: type)
            )
        )
        withMutation(keyPath: \.transcript) {
            state.withLock { $0.transcript.append(promptEntry) }
        }

        return wrapStream(
            model.streamResponse(
                within: self,
                to: prompt,
                generating: type,
                includeSchemaInPrompt: includeSchemaInPrompt,
                options: options
            ),
            promptEntry: promptEntry
        )
    }
}

// MARK: - String Response Convenience Methods

extension LanguageModelSession {
    @discardableResult
    nonisolated public func respond(
        to prompt: Prompt,
        options: GenerationOptions = GenerationOptions()
    ) async throws -> Response<String> {
        try await respond(
            to: prompt,
            generating: String.self,
            includeSchemaInPrompt: true,
            options: options
        )
    }

    @discardableResult
    nonisolated public func respond(
        to prompt: String,
        options: GenerationOptions = GenerationOptions()
    ) async throws -> Response<String> {
        try await respond(to: Prompt(prompt), options: options)
    }

    @discardableResult
    nonisolated public func respond(
        options: GenerationOptions = GenerationOptions(),
        @PromptBuilder prompt: () throws -> Prompt
    ) async throws -> Response<String> {
        try await respond(to: try prompt(), options: options)
    }

    public func streamResponse(
        to prompt: Prompt,
        options: GenerationOptions = GenerationOptions()
    ) -> sending ResponseStream<String> {
        streamResponse(
            to: prompt,
            generating: String.self,
            includeSchemaInPrompt: true,
            options: options
        )
    }

    public func streamResponse(
        to prompt: String,
        options: GenerationOptions = GenerationOptions()
    ) -> sending ResponseStream<String> {
        streamResponse(to: Prompt(prompt), options: options)
    }

    public func streamResponse(
        options: GenerationOptions = GenerationOptions(),
        @PromptBuilder prompt: () throws -> Prompt
    ) rethrows -> sending ResponseStream<String> {
        streamResponse(to: try prompt(), options: options)
    }
}

// MARK: - GeneratedContent with Schema Convenience Methods

extension LanguageModelSession {
    /// Generates content that conforms to the supplied schema.
    /// Provider restrictions still apply; OpenAI strict mode requires an object root.
    @discardableResult
    nonisolated public func respond(
        to prompt: Prompt,
        schema: GenerationSchema,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) async throws -> Response<GeneratedContent> {
        try await respond(to: prompt, responseFormat: .init(schema: schema), options: options) {
            try await model.respond(
                within: self,
                to: prompt,
                schema: schema,
                includeSchemaInPrompt: includeSchemaInPrompt,
                options: options
            )
        }
    }

    /// Generates content that conforms to the supplied schema.
    /// Provider restrictions still apply; OpenAI strict mode requires an object root.
    @discardableResult
    nonisolated public func respond(
        to prompt: String,
        schema: GenerationSchema,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) async throws -> Response<GeneratedContent> {
        try await respond(
            to: Prompt(prompt),
            schema: schema,
            includeSchemaInPrompt: includeSchemaInPrompt,
            options: options
        )
    }

    /// Generates content that conforms to the supplied schema.
    /// Provider restrictions still apply; OpenAI strict mode requires an object root.
    @discardableResult
    nonisolated public func respond(
        schema: GenerationSchema,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions(),
        @PromptBuilder prompt: () throws -> Prompt
    ) async throws -> Response<GeneratedContent> {
        try await respond(
            to: try prompt(),
            schema: schema,
            includeSchemaInPrompt: includeSchemaInPrompt,
            options: options
        )
    }

    /// Streams content that conforms to the supplied schema.
    /// Provider restrictions still apply; OpenAI strict mode requires an object root.
    nonisolated public func streamResponse(
        to prompt: Prompt,
        schema: GenerationSchema,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) -> sending ResponseStream<GeneratedContent> {
        let promptEntry = Transcript.Entry.prompt(
            Transcript.Prompt(
                segments: [.text(.init(content: prompt.description))],
                options: options,
                responseFormat: .init(schema: schema)
            )
        )
        withMutation(keyPath: \.transcript) {
            state.withLock { $0.transcript.append(promptEntry) }
        }

        return wrapStream(
            model.streamResponse(
                within: self,
                to: prompt,
                schema: schema,
                includeSchemaInPrompt: includeSchemaInPrompt,
                options: options
            ),
            promptEntry: promptEntry
        )
    }

    /// Streams content that conforms to the supplied schema.
    /// Provider restrictions still apply; OpenAI strict mode requires an object root.
    nonisolated public func streamResponse(
        to prompt: String,
        schema: GenerationSchema,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) -> sending ResponseStream<GeneratedContent> {
        streamResponse(
            to: Prompt(prompt),
            schema: schema,
            includeSchemaInPrompt: includeSchemaInPrompt,
            options: options
        )
    }

    /// Streams content that conforms to the supplied schema.
    /// Provider restrictions still apply; OpenAI strict mode requires an object root.
    nonisolated public func streamResponse(
        schema: GenerationSchema,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions(),
        @PromptBuilder prompt: () throws -> Prompt
    ) rethrows -> sending ResponseStream<GeneratedContent> {
        streamResponse(to: try prompt(), schema: schema, includeSchemaInPrompt: includeSchemaInPrompt, options: options)
    }
}

// MARK: - Generic Content Convenience Methods

extension LanguageModelSession {
    @discardableResult
    nonisolated public func respond<Content>(
        to prompt: String,
        generating type: Content.Type = Content.self,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) async throws -> Response<Content> where Content: Generable {
        try await respond(
            to: Prompt(prompt),
            generating: type,
            includeSchemaInPrompt: includeSchemaInPrompt,
            options: options
        )
    }

    @discardableResult
    nonisolated public func respond<Content>(
        generating type: Content.Type = Content.self,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions(),
        @PromptBuilder prompt: () throws -> Prompt
    ) async throws -> Response<Content> where Content: Generable {
        try await respond(
            to: try prompt(),
            generating: type,
            includeSchemaInPrompt: includeSchemaInPrompt,
            options: options
        )
    }

    nonisolated public func streamResponse<Content>(
        to prompt: String,
        generating type: Content.Type = Content.self,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) -> sending ResponseStream<Content> where Content: Generable {
        streamResponse(
            to: Prompt(prompt),
            generating: type,
            includeSchemaInPrompt: includeSchemaInPrompt,
            options: options
        )
    }

    public func streamResponse<Content>(
        generating type: Content.Type = Content.self,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions(),
        @PromptBuilder prompt: () throws -> Prompt
    ) rethrows -> sending ResponseStream<Content> where Content: Generable {
        streamResponse(
            to: try prompt(),
            generating: type,
            includeSchemaInPrompt: includeSchemaInPrompt,
            options: options
        )
    }
}

// MARK: - Image Convenience Methods

extension LanguageModelSession {
    @discardableResult
    nonisolated public func respond(
        to prompt: String,
        image: Transcript.ImageSegment,
        options: GenerationOptions = GenerationOptions()
    ) async throws -> Response<String> {
        try await respond(
            to: prompt,
            images: [image],
            options: options
        )
    }

    @discardableResult
    nonisolated public func respond(
        to prompt: String,
        images: [Transcript.ImageSegment],
        options: GenerationOptions = GenerationOptions()
    ) async throws -> Response<String> {
        try await respond(
            to: prompt,
            images: images,
            generating: String.self,
            includeSchemaInPrompt: true,
            options: options
        )
    }

    @discardableResult
    nonisolated public func respond<Content>(
        to prompt: String,
        image: Transcript.ImageSegment,
        generating type: Content.Type = Content.self,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) async throws -> Response<Content> where Content: Generable {
        try await respond(
            to: prompt,
            images: [image],
            generating: type,
            includeSchemaInPrompt: includeSchemaInPrompt,
            options: options
        )
    }

    @discardableResult
    nonisolated public func respond<Content>(
        to prompt: String,
        images: [Transcript.ImageSegment],
        generating type: Content.Type = Content.self,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) async throws -> Response<Content> where Content: Generable {
        try await wrapRespond { promptID in
            // Build segments from text and images
            var segments: [Transcript.Segment] = []
            if !prompt.isEmpty {
                segments.append(.text(.init(content: prompt)))
            }
            segments.append(contentsOf: images.map { .image($0) })

            // Add prompt to transcript
            let promptEntry = Transcript.Entry.prompt(
                Transcript.Prompt(
                    id: promptID,
                    segments: segments,
                    options: options,
                    responseFormat: type == String.self ? nil : .init(type: type)
                )
            )
            withMutation(keyPath: \.transcript) {
                state.withLock { $0.transcript.append(promptEntry) }
            }

            // Extract text content for the Prompt parameter
            let textPrompt = Prompt(prompt)

            let response = try await model.respond(
                within: self,
                to: textPrompt,
                generating: type,
                includeSchemaInPrompt: includeSchemaInPrompt,
                options: options
            )

            recordUsage(response.usage)

            // Add response entry to transcript
            let textContent: String
            if case .string(let str) = response.rawContent.kind {
                textContent = str
            } else {
                textContent = response.rawContent.jsonString
            }

            let responseEntry = Transcript.Entry.response(
                Transcript.Response(
                    assetIDs: [],
                    segments: [.text(.init(content: textContent))],
                    providerMetadata: response.providerMetadata
                )
            )

            // Add tool entries and response to transcript
            withMutation(keyPath: \.transcript) {
                state.withLock { lockedState in
                    lockedState.transcript.append(contentsOf: response.transcriptEntries)
                    lockedState.transcript.append(responseEntry)
                }
            }

            return response
        }
    }

    public func streamResponse(
        to prompt: String,
        image: Transcript.ImageSegment,
        options: GenerationOptions = GenerationOptions()
    ) -> sending ResponseStream<String> {
        streamResponse(
            to: prompt,
            images: [image],
            options: options
        )
    }

    public func streamResponse(
        to prompt: String,
        images: [Transcript.ImageSegment],
        options: GenerationOptions = GenerationOptions()
    ) -> sending ResponseStream<String> {
        streamResponse(
            to: prompt,
            images: images,
            generating: String.self,
            includeSchemaInPrompt: true,
            options: options
        )
    }

    nonisolated public func streamResponse<Content>(
        to prompt: String,
        image: Transcript.ImageSegment,
        generating type: Content.Type = Content.self,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) -> sending ResponseStream<Content> where Content: Generable {
        streamResponse(
            to: prompt,
            images: [image],
            generating: type,
            includeSchemaInPrompt: includeSchemaInPrompt,
            options: options
        )
    }

    nonisolated public func streamResponse<Content>(
        to prompt: String,
        images: [Transcript.ImageSegment],
        generating type: Content.Type = Content.self,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) -> sending ResponseStream<Content> where Content: Generable {
        // Build segments from text and images
        var segments: [Transcript.Segment] = []
        if !prompt.isEmpty {
            segments.append(.text(.init(content: prompt)))
        }
        segments.append(contentsOf: images.map { .image($0) })

        // Create prompt entry that will be added when stream starts
        let promptEntry = Transcript.Entry.prompt(
            Transcript.Prompt(
                segments: segments,
                options: options,
                responseFormat: type == String.self ? nil : .init(type: type)
            )
        )
        withMutation(keyPath: \.transcript) {
            state.withLock { $0.transcript.append(promptEntry) }
        }

        // Extract text content for the Prompt parameter
        let textPrompt = Prompt(prompt)

        return wrapStream(
            model.streamResponse(
                within: self,
                to: textPrompt,
                generating: type,
                includeSchemaInPrompt: includeSchemaInPrompt,
                options: options
            ),
            promptEntry: promptEntry
        )
    }
}

// MARK: -

extension LanguageModelSession {
    @discardableResult
    public func logFeedbackAttachment(
        sentiment: LanguageModelFeedback.Sentiment?,
        issues: [LanguageModelFeedback.Issue] = [],
        desiredOutput: Transcript.Entry? = nil
    ) -> Data {
        model.logFeedbackAttachment(
            within: self,
            sentiment: sentiment,
            issues: issues,
            desiredOutput: desiredOutput
        )
    }
}

// MARK: -

extension LanguageModelSession {
    public enum GenerationError: Error, LocalizedError {
        public struct Context: Sendable {
            public let debugDescription: String

            public init(debugDescription: String) {
                self.debugDescription = debugDescription
            }
        }

        public struct Refusal: Sendable {
            public let transcriptEntries: [Transcript.Entry]

            public init(transcriptEntries: [Transcript.Entry]) {
                self.transcriptEntries = transcriptEntries
            }

            public var explanation: Response<String> {
                get async throws {
                    // Extract explanation from transcript entries
                    let explanationText = transcriptEntries.compactMap { entry in
                        if case .response(let response) = entry {
                            return response.segments.compactMap { segment in
                                if case .text(let textSegment) = segment {
                                    return textSegment.content
                                }
                                return nil
                            }.joined(separator: " ")
                        }
                        return nil
                    }.joined(separator: "\n")

                    return Response(
                        content: explanationText.isEmpty ? "No explanation available" : explanationText,
                        rawContent: GeneratedContent(
                            explanationText.isEmpty ? "No explanation available" : explanationText
                        ),
                        transcriptEntries: ArraySlice(transcriptEntries)
                    )
                }
            }

            public var explanationStream: ResponseStream<String> {
                // Create a simple stream that yields the explanation text
                let explanationText = transcriptEntries.compactMap { entry in
                    if case .response(let response) = entry {
                        return response.segments.compactMap { segment in
                            if case .text(let textSegment) = segment {
                                return textSegment.content
                            }
                            return nil
                        }.joined(separator: " ")
                    }
                    return nil
                }.joined(separator: "\n")

                let finalText = explanationText.isEmpty ? "No explanation available" : explanationText
                return ResponseStream(content: finalText, rawContent: GeneratedContent(finalText))
            }
        }

        case exceededContextWindowSize(Context)
        case assetsUnavailable(Context)
        case guardrailViolation(Context)
        case unsupportedGuide(Context)
        case unsupportedLanguageOrLocale(Context)
        case decodingFailure(Context)
        case rateLimited(Context)
        case concurrentRequests(Context)
        case refusal(Refusal, Context)

        public var errorDescription: String? { nil }
        public var recoverySuggestion: String? { nil }
        public var failureReason: String? { nil }
    }

    public struct ToolCallError: Error, LocalizedError {
        public var tool: any Tool
        public var underlyingError: any Error

        public init(tool: any Tool, underlyingError: any Error) {
            self.tool = tool
            self.underlyingError = underlyingError
        }

        public var errorDescription: String? { nil }
    }
}

extension LanguageModelSession {
    /// An asynchronous sequence of snapshots of a model response.
    public struct ResponseStream<Content>: Sendable where Content: Generable, Content.PartiallyGenerated: Sendable {
        private let fallbackSnapshot: Snapshot?
        private let streaming: AsyncThrowingStream<Snapshot, any Error>?

        /// Creates a response stream that yields a single snapshot.
        /// - Parameters:
        ///   - content: The complete response content.
        ///   - rawContent: The raw content produced by the model.
        ///   - usage: Provider-reported token usage.
        public init(
            content: Content,
            rawContent: GeneratedContent,
            usage: Usage = .init(
                input: .init(totalTokenCount: 0, cachedTokenCount: 0),
                output: .init(totalTokenCount: 0, reasoningTokenCount: 0)
            )
        ) {
            self.fallbackSnapshot = Snapshot(
                content: content.asPartiallyGenerated(),
                rawContent: rawContent,
                usage: usage
            )
            self.streaming = nil
        }

        /// Creates a response stream that yields snapshots from an async stream.
        /// - Parameter stream: The snapshot stream to relay.
        public init(stream: AsyncThrowingStream<Snapshot, any Error>) {
            // When streaming, snapshots arrive from the upstream sequence, so no fallback is required.
            self.fallbackSnapshot = nil
            self.streaming = stream
        }

        /// A snapshot of partially generated content and response metadata.
        public struct Snapshot: Sendable where Content.PartiallyGenerated: Sendable {
            /// The partially generated response content.
            public var content: Content.PartiallyGenerated

            /// The raw content produced so far by the model.
            public var rawContent: GeneratedContent

            /// Transcript entries (reasoning, tool calls and outputs) produced so far while streaming.
            /// Cumulative across tool rounds;
            /// empty for providers that don't stream tool activity.
            public var transcriptEntries: ArraySlice<Transcript.Entry>

            /// Provider-reported counts so far,
            /// with zero counts for values the provider does not report.
            public var usage: Usage

            internal var providerMetadata: [String: String]?

            /// Creates a snapshot from partially generated content and raw content.
            /// - Parameters:
            ///   - content: The partially generated content.
            ///   - rawContent: The raw content produced by the model.
            ///   - transcriptEntries: Transcript entries accumulated so far (reasoning/tool calls/outputs).
            ///   - usage: Provider-reported token usage so far.
            public init(
                content: Content.PartiallyGenerated,
                rawContent: GeneratedContent,
                transcriptEntries: ArraySlice<Transcript.Entry> = [],
                usage: Usage = .init(
                    input: .init(totalTokenCount: 0, cachedTokenCount: 0),
                    output: .init(totalTokenCount: 0, reasoningTokenCount: 0)
                )
            ) {
                self.init(
                    content: content,
                    rawContent: rawContent,
                    transcriptEntries: transcriptEntries,
                    usage: usage,
                    providerMetadata: nil
                )
            }

            internal init(
                content: Content.PartiallyGenerated,
                rawContent: GeneratedContent,
                transcriptEntries: ArraySlice<Transcript.Entry> = [],
                usage: Usage = .init(
                    input: .init(totalTokenCount: 0, cachedTokenCount: 0),
                    output: .init(totalTokenCount: 0, reasoningTokenCount: 0)
                ),
                providerMetadata: [String: String]?
            ) {
                self.content = content
                self.rawContent = rawContent
                self.transcriptEntries = transcriptEntries
                self.usage = usage
                self.providerMetadata = providerMetadata
            }
        }
    }
}

extension LanguageModelSession.ResponseStream: AsyncSequence {
    public typealias Element = Snapshot

    public struct AsyncIterator: AsyncIteratorProtocol {
        private var hasYielded = false
        private let fallbackSnapshot: Snapshot?
        private var streamIterator: AsyncThrowingStream<Snapshot, any Error>.AsyncIterator?
        private let useStream: Bool

        init(fallbackSnapshot: Snapshot?, stream: AsyncThrowingStream<Snapshot, any Error>?) {
            self.fallbackSnapshot = fallbackSnapshot
            self.streamIterator = stream?.makeAsyncIterator()
            self.useStream = stream != nil
        }

        public mutating func next() async throws -> Snapshot? {
            if useStream {
                if var iterator = streamIterator {
                    if let value = try await iterator.next() {
                        // store back the advanced iterator
                        streamIterator = iterator
                        return value
                    }
                    streamIterator = iterator
                }
                return nil
            } else {
                guard !hasYielded, let fallbackSnapshot else { return nil }
                hasYielded = true
                return fallbackSnapshot
            }
        }

        public typealias Element = Snapshot
    }

    public func makeAsyncIterator() -> AsyncIterator {
        return AsyncIterator(fallbackSnapshot: fallbackSnapshot, stream: streaming)
    }

    nonisolated public func collect() async throws -> sending LanguageModelSession.Response<Content> {
        if let streaming {
            var last: Snapshot?
            for try await snapshot in streaming {
                last = snapshot
            }
            if let last {
                // Attempt to materialize a concrete Content from the last snapshot
                let finalContent: Content
                if let concrete = last.content as? Content {
                    finalContent = concrete
                } else {
                    finalContent = try Content(last.rawContent)
                }
                return LanguageModelSession.Response(
                    content: finalContent,
                    rawContent: last.rawContent,
                    transcriptEntries: last.transcriptEntries,
                    usage: last.usage,
                    providerMetadata: last.providerMetadata
                )
            }
        }

        if let fallbackSnapshot {
            let finalContent: Content
            if let concrete = fallbackSnapshot.content as? Content {
                finalContent = concrete
            } else {
                finalContent = try Content(fallbackSnapshot.rawContent)
            }
            return LanguageModelSession.Response(
                content: finalContent,
                rawContent: fallbackSnapshot.rawContent,
                transcriptEntries: fallbackSnapshot.transcriptEntries,
                usage: fallbackSnapshot.usage,
                providerMetadata: fallbackSnapshot.providerMetadata
            )
        }

        throw ResponseStreamError.noSnapshots
    }
}

private enum ResponseStreamError: Error, LocalizedError {
    case noSnapshots

    var errorDescription: String? {
        switch self {
        case .noSnapshots:
            return "The response stream ended without producing a snapshot."
        }
    }
}

// MARK: -

private struct State: Equatable, Sendable {
    var transcript: Transcript
    var transcriptErrorHandlingPolicy: TranscriptErrorHandlingPolicy?
    var usage = LanguageModelSession.Usage.zero

    var isResponding: Bool { count > 0 }
    private var count = 0

    init(_ transcript: Transcript) {
        self.transcript = transcript
    }

    mutating func beginResponding() {
        count += 1
    }

    mutating func endResponding() {
        count = max(0, count - 1)
    }
}
