import Foundation
import Observation

/// Controls transcript retention when generation fails or is cancelled.
///
/// - Note: This API is exclusive to AnyLanguageModel
///   and using it means your code is no longer drop-in compatible
///   with the Foundation Models framework.
public struct TranscriptErrorHandlingPolicy: Sendable, Equatable {
    private let shouldRevert: Bool

    /// Retain the prompt and the latest cumulative streaming checkpoint.
    /// Nonstreaming failures have no checkpoint and retain only the prompt.
    public static let preserveTranscript = Self(shouldRevert: false)
    /// Remove entries added by the failing request, preserving other requests.
    /// Tool side effects are not undone.
    public static let revertTranscript = Self(shouldRevert: true)
}

@Observable
public final class LanguageModelSession: @unchecked Sendable {
    public var isResponding: Bool {
        access(keyPath: \.isResponding)
        return state.withLock { $0.isResponding }
    }

    /// On failure, `nil` retains the prompt without committing streaming checkpoints.
    /// Streaming cancellation never commits the partial answer as a completed response, regardless
    /// of this policy. These defaults do not claim Foundation Models behavioral parity.
    ///
    /// - Note: This property is exclusive to AnyLanguageModel
    ///   and using it means your code is no longer drop-in compatible
    ///   with the Foundation Models framework.
    public var transcriptErrorHandlingPolicy: TranscriptErrorHandlingPolicy? {
        get {
            access(keyPath: \.transcriptErrorHandlingPolicy)
            return state.withLock { $0.transcriptErrorHandlingPolicy }
        }
        set {
            withMutation(keyPath: \.transcriptErrorHandlingPolicy) {
                state.withLock { $0.transcriptErrorHandlingPolicy = newValue }
            }
        }
    }

    public var transcript: Transcript {
        access(keyPath: \.transcript)
        return state.withLock { $0.transcript }
    }

    /// The accumulated token usage across responses generated by this session.
    ///
    /// Counts increase as responses and streaming snapshots report usage.
    /// Restoring a transcript does not restore usage from previous sessions.
    ///
    /// - Note: This property is exclusive to AnyLanguageModel on OS 26.
    ///   It follows the Foundation Models 27 `LanguageModelSession.usage` API,
    ///   so code that uses it ports to Foundation Models on OS 27.
    public var usage: Usage {
        access(keyPath: \.usage)
        return state.withLock { $0.usage }
    }

    @ObservationIgnored private let state: Locked<State>

    @ObservationIgnored private let responseRelays = Locked<[UUID: Task<Void, Never>]>([:])

    /// Waits for transcript cleanup of all streaming relays registered when this call begins.
    ///
    /// Relays started later are excluded.
    /// Cancelling this wait does not cancel generation.
    /// Call after cancelling consumers and before persisting the transcript.
    /// Nonstreaming operations must be awaited separately.
    /// Do not call from a tool executing within one of the included responses.
    ///
    /// - Note: This API is exclusive to AnyLanguageModel
    ///   and using it means your code is no longer drop-in compatible
    ///   with the Foundation Models framework.
    nonisolated public func waitForResponseCompletion() async {
        let tasks = responseRelays.withLock { Array($0.values) }
        for task in tasks { await task.value }
    }

    private let model: any LanguageModel

    /// The tools that the model can call during the session.
    ///
    /// For a session created with dynamic instructions, this is empty.
    /// Call ``resolvedRequestContext()`` to get the tools for the next request.
    ///
    /// - Note: This property is exclusive to AnyLanguageModel
    ///   and using it means your code is no longer drop-in compatible
    ///   with the Foundation Models framework.
    ///   It's public so that language models outside this module
    ///   can read the session's tools.
    public let tools: [any Tool]

    /// The instructions for the session, if any.
    ///
    /// For a session created with dynamic instructions, this is `nil`.
    /// Call ``resolvedRequestContext()`` to get the instructions for the next request.
    ///
    /// - Note: This property is exclusive to AnyLanguageModel
    ///   and using it means your code is no longer drop-in compatible
    ///   with the Foundation Models framework.
    ///   It's public so that language models outside this module
    ///   can read the session's instructions.
    public let instructions: Instructions?

    private let dynamicInstructions: AnyDynamicInstructions?
    private let dynamicProfile: AnyDynamicProfile?
    private let dynamicInstructionsLock = NSLock()
    private let dynamicProfileLock = NSLock()
    private let profileLifecycle = ProfileLifecycle()

    /// Session-scoped values available to profiles, dynamic instructions, and Tools.
    public let properties: SessionPropertyValues

    /// Whether the session resolves its instructions and tools before each request.
    nonisolated var usesDynamicInstructions: Bool {
        dynamicInstructions != nil || dynamicProfile != nil
    }

    /// A delegate that observes and controls tool execution.
    ///
    /// Set this property to intercept tool calls, provide custom output,
    /// or stop after tool calls are generated.
    ///
    /// - Note: This property is exclusive to AnyLanguageModel
    ///   and using it means your code is no longer drop-in compatible
    ///   with the Foundation Models framework.
    @ObservationIgnored public var toolExecutionDelegate: (any ToolExecutionDelegate)?

    /// The transcript, instructions, and tools for one model request.
    ///
    /// A language model creates one context immediately before each request it sends,
    /// by calling ``LanguageModelSession/resolvedRequestContext()``.
    /// If that request produces tool calls,
    /// run them with the ``tools`` from the same context,
    /// and resolve a new context only before the continuation request.
    ///
    /// - Note: This API is exclusive to AnyLanguageModel
    ///   and using it means your code is no longer drop-in compatible
    ///   with the Foundation Models framework.
    ///   It's public so that language models outside this module
    ///   can read the inputs for each request.
    public struct RequestContext: Sendable {
        /// The transcript to send with the request.
        public let transcript: Transcript

        /// The instructions for the request, if any.
        public let instructions: Instructions?

        /// The tools that the model can call in response to the request.
        public let tools: [any Tool]

        /// The model selected for this request.
        public let model: any LanguageModel

        /// Generation options after profile defaults are combined with call-site options.
        public let options: GenerationOptions

        /// Context options selected by the active profile.
        public let contextOptions: ContextOptions

        /// Transcript failure behavior captured for this request.
        public let transcriptErrorHandlingPolicy: TranscriptErrorHandlingPolicy?

        fileprivate let profile: ResolvedDynamicProfile?
        fileprivate let canonicalTranscript: [Transcript.Entry]
        fileprivate let callbackState: ProfileCallbackState

        fileprivate init(
            transcript: Transcript,
            instructions: Instructions?,
            tools: [any Tool],
            model: any LanguageModel,
            options: GenerationOptions = .init(),
            contextOptions: ContextOptions = .init(),
            transcriptErrorHandlingPolicy: TranscriptErrorHandlingPolicy? = nil,
            profile: ResolvedDynamicProfile? = nil,
            canonicalTranscript: [Transcript.Entry]? = nil,
            callbackState: ProfileCallbackState = ProfileCallbackState()
        ) {
            self.transcript = transcript
            self.instructions = instructions
            self.tools = tools
            self.model = model
            self.options = options
            self.contextOptions = contextOptions
            self.transcriptErrorHandlingPolicy = transcriptErrorHandlingPolicy
            self.profile = profile
            self.canonicalTranscript = canonicalTranscript ?? Array(transcript)
            self.callbackState = callbackState
        }

        fileprivate func sharingCallbackState(with context: RequestContext) -> RequestContext {
            RequestContext(
                transcript: transcript,
                instructions: instructions,
                tools: tools,
                model: model,
                options: options,
                contextOptions: contextOptions,
                transcriptErrorHandlingPolicy: transcriptErrorHandlingPolicy,
                profile: profile,
                canonicalTranscript: canonicalTranscript,
                callbackState: context.callbackState
            )
        }
    }

    /// Returns the transcript, instructions, and tools for the next model request.
    ///
    /// Calling this method doesn't change the session.
    ///
    /// - Note: This API is exclusive to AnyLanguageModel
    ///   and using it means your code is no longer drop-in compatible
    ///   with the Foundation Models framework.
    ///   It's public so that language models outside this module
    ///   can read the inputs for each request.
    nonisolated public func resolvedRequestContext() -> RequestContext {
        if let prepared = ProfileRequestBinding.prepared,
            prepared.session === self
        {
            return prepared.context
        }
        return resolveRequestContext(additionalEntries: [], options: .init())
    }

    /// Resolves the active profile for one actual model request.
    ///
    /// `additionalEntries` supplies canonical entries produced in the current Tool
    /// round but not yet committed to the durable Session transcript. A profile's
    /// history transform sees those entries before selecting the request projection.
    ///
    /// - Note: This overload is exclusive to AnyLanguageModel. Compatibility
    ///   executors use it to preserve Foundation Models 27 request timing while
    ///   AnyLanguageModel still exposes its legacy model interface.
    nonisolated public func resolvedRequestContext(
        including additionalEntries: [Transcript.Entry],
        options: GenerationOptions = .init()
    ) async throws -> RequestContext {
        let prepared = ProfileRequestBinding.prepared
        if additionalEntries.isEmpty, let prepared, prepared.session === self {
            return prepared.context
        }
        let callSiteOptions =
            if let prepared, prepared.session === self {
                prepared.callSiteOptions
            } else {
                options
            }
        var context = resolveRequestContext(
            additionalEntries: additionalEntries,
            options: callSiteOptions
        )
        if let prepared, prepared.session === self {
            context = context.sharingCallbackState(with: prepared.context)
        }
        if let profile = context.profile {
            try await profileLifecycle.prepare(
                profile,
                properties: properties,
                history: context.canonicalTranscript,
                protectedEntryIDs: Set(additionalEntries.map(\.id))
            )
        }
        if let prepared, prepared.session === self {
            prepared.context = context
        }
        return context
    }

    nonisolated private func resolveRequestContext(
        additionalEntries: [Transcript.Entry],
        options: GenerationOptions
    ) -> RequestContext {
        var canonical = Array(transcript) + additionalEntries
        let sessionErrorPolicy = transcriptErrorHandlingPolicy
        guard let dynamicProfile else {
            guard let dynamicInstructions else {
                return RequestContext(
                    transcript: Transcript(entries: canonical),
                    instructions: instructions,
                    tools: tools,
                    model: model,
                    options: options,
                    transcriptErrorHandlingPolicy: sessionErrorPolicy,
                    canonicalTranscript: canonical
                )
            }

            // Dynamic instructions are request-only. Their body can observe
            // session properties and canonical history, but cannot rewrite history.
            let history = properties.historyBinding(canonical, isWritable: false)
            let resolved = dynamicInstructionsLock.withLock {
                SessionPropertyBinding.$values.withValue(properties) {
                    SessionPropertyBinding.$history.withValue(history) {
                        dynamicInstructions.resolveForRequest()
                    }
                }
            }
            var requestTranscript = Transcript(entries: canonical)
            if let currentInstructions = resolved.instructions {
                requestTranscript = Transcript(
                    entries: [instructionsEntry(currentInstructions, tools: resolved.tools)] + canonical
                )
            }
            return RequestContext(
                transcript: requestTranscript,
                instructions: resolved.instructions,
                tools: resolved.tools,
                model: model,
                options: options,
                transcriptErrorHandlingPolicy: sessionErrorPolicy,
                canonicalTranscript: canonical
            )
        }

        let protectedEntryIDs = Set(additionalEntries.map(\.id))
        let history = properties.historyBinding(
            canonical,
            isWritable: true,
            protecting: protectedEntryIDs
        )
        let resolved = dynamicProfileLock.withLock {
            SessionPropertyBinding.$values.withValue(properties) {
                SessionPropertyBinding.$history.withValue(history) {
                    dynamicProfile.resolveForRequest()
                }
            }
        }
        canonical = history.entries
        var projected = canonical
        for transform in resolved.historyTransforms {
            let transformHistory = properties.historyBinding(
                canonical,
                isWritable: true,
                protecting: protectedEntryIDs
            )
            projected = SessionPropertyBinding.$values.withValue(properties) {
                SessionPropertyBinding.$history.withValue(transformHistory) {
                    transform(projected)
                }
            }
            canonical = transformHistory.entries
        }
        var requestTranscript = Transcript(entries: projected)
        if let currentInstructions = resolved.instructions {
            requestTranscript = Transcript(
                entries: [instructionsEntry(currentInstructions, tools: resolved.tools)] + projected
            )
        }

        var resolvedOptions = options
        if resolvedOptions.sampling == nil, resolved.hasSamplingMode {
            resolvedOptions.sampling = resolved.samplingMode
        }
        if resolvedOptions.temperature == nil, resolved.hasTemperature {
            resolvedOptions.temperature = resolved.temperature
        }
        if resolvedOptions.maximumResponseTokens == nil, resolved.hasMaximumResponseTokens {
            resolvedOptions.maximumResponseTokens = resolved.maximumResponseTokens
        }
        if resolvedOptions.toolCallingMode == nil, resolved.hasToolCallingMode {
            resolvedOptions.toolCallingMode = resolved.toolCallingMode
        }
        return RequestContext(
            transcript: requestTranscript,
            instructions: resolved.instructions,
            tools: resolved.tools,
            model: resolved.model ?? model,
            options: resolvedOptions,
            contextOptions: .init(reasoningLevel: resolved.reasoningLevel),
            transcriptErrorHandlingPolicy: resolved.hasTranscriptErrorHandlingPolicy
                ? resolved.transcriptErrorHandlingPolicy
                : sessionErrorPolicy,
            profile: resolved,
            canonicalTranscript: canonical
        )
    }

    nonisolated private func instructionsEntry(
        _ instructions: Instructions,
        tools: [any Tool]
    ) -> Transcript.Entry {
        .instructions(
            .init(
                segments: [.text(.init(content: instructions.description))],
                toolDefinitions:
                    tools
                    .filter(\.includesSchemaInInstructions)
                    .map { Transcript.ToolDefinition(tool: $0) }
            )
        )
    }

    /// Runs the active request snapshot's Tool-call callbacks.
    nonisolated public func profileWillExecuteToolCall(
        _ call: Transcript.ToolCall,
        requestContext: RequestContext,
        currentRoundEntries: [Transcript.Entry]
    ) async throws {
        guard let profile = requestContext.profile else { return }
        let history = Array(transcript) + currentRoundEntries
        try await withSessionProperties(
            history: history,
            isHistoryWritable: true,
            protectedEntryIDs: Set(currentRoundEntries.map(\.id))
        ) {
            for action in profile.onToolCall { try await action(call) }
        }
    }

    /// Runs the active request snapshot's Tool-output callbacks.
    nonisolated public func profileDidProduceToolOutput(
        for call: Transcript.ToolCall,
        output: Transcript.ToolOutput,
        requestContext: RequestContext,
        currentRoundEntries: [Transcript.Entry]
    ) async throws {
        guard let profile = requestContext.profile else { return }
        let history = Array(transcript) + currentRoundEntries
        try await withSessionProperties(
            history: history,
            isHistoryWritable: true,
            protectedEntryIDs: Set(currentRoundEntries.map(\.id))
        ) {
            for action in profile.onToolOutput { try await action(call, output) }
        }
    }

    /// Runs reasoning and response callbacks from the profile snapshot that
    /// produced the entries. Each stable entry ID is dispatched at most once
    /// for the active request, including when streaming snapshots repeat it.
    ///
    /// - Note: This API is exclusive to AnyLanguageModel's compatibility model
    ///   seam. Ordinary callers compose callbacks through ``DynamicProfile``.
    nonisolated public func profileDidProduceEntries(
        _ entries: [Transcript.Entry],
        requestContext: RequestContext,
        currentRoundEntries: [Transcript.Entry]
    ) async throws {
        guard let profile = requestContext.profile else { return }
        for entry in entries {
            if requestContext.callbackState.wasDispatched(entry.id) {
                continue
            }
            let history = Array(transcript) + currentRoundEntries
            switch entry {
            case .reasoning(let reasoning):
                try await withSessionProperties(
                    history: history,
                    isHistoryWritable: true,
                    protectedEntryIDs: Set(currentRoundEntries.map(\.id))
                ) {
                    for action in profile.onReasoning { try await action(reasoning) }
                }
            case .response(let response):
                try await withSessionProperties(
                    history: history,
                    isHistoryWritable: true,
                    protectedEntryIDs: Set(currentRoundEntries.map(\.id))
                ) {
                    for action in profile.onResponse { try await action(response) }
                }
            default:
                continue
            }
            requestContext.callbackState.markDispatched(entry.id)
        }
    }

    /// Executes compatibility-model Tool work with session properties bound to
    /// the producing request. Custom properties remain mutable, while the
    /// canonical history is read-only in a Tool, matching Foundation Models 27.
    nonisolated public func withProfileToolExecution<Result: Sendable>(
        requestContext: RequestContext,
        currentRoundEntries: [Transcript.Entry],
        operation: @Sendable () async throws -> Result
    ) async rethrows -> Result {
        let history = Array(transcript) + currentRoundEntries
        return try await withSessionProperties(
            history: history,
            isHistoryWritable: false,
            protectedEntryIDs: Set(currentRoundEntries.map(\.id))
        ) {
            try await operation()
        }
    }

    nonisolated private func withSessionProperties<Result: Sendable>(
        history: [Transcript.Entry],
        isHistoryWritable: Bool,
        protectedEntryIDs: Set<String> = [],
        operation: @Sendable () async throws -> Result
    ) async rethrows -> Result {
        let history = properties.historyBinding(
            history,
            isWritable: isHistoryWritable,
            protecting: protectedEntryIDs
        )
        return try await SessionPropertyBinding.$values.withValue(properties) {
            try await SessionPropertyBinding.$history.withValue(history) {
                try await operation()
            }
        }
    }

    /// Creates a session with a model, tools,
    /// and instructions that you build with a result builder.
    ///
    /// - Note: Unlike Foundation Models,
    ///   which defaults `model` to `SystemLanguageModel.default`,
    ///   AnyLanguageModel requires the `model` argument
    ///   and accepts any type that conforms to ``LanguageModel``.
    ///   Code that omits `model` doesn't compile with AnyLanguageModel;
    ///   pass `SystemLanguageModel.default` to use the system model.
    ///   Code that passes another model
    ///   is no longer drop-in compatible with the Foundation Models framework.
    public convenience init(
        model: any LanguageModel,
        tools: [any Tool] = [],
        @InstructionsBuilder instructions: () throws -> Instructions
    ) rethrows {
        try self.init(model: model, tools: tools, instructions: instructions())
    }

    /// Creates a session with a model, tools, and instructions as a string.
    ///
    /// - Note: Unlike Foundation Models,
    ///   AnyLanguageModel requires the `model` argument
    ///   and accepts any ``LanguageModel``.
    public convenience init(
        model: any LanguageModel,
        tools: [any Tool] = [],
        instructions: String
    ) {
        self.init(model: model, tools: tools, instructions: Instructions(instructions), transcript: Transcript())
    }

    /// Creates a session with a model, tools, and optional instructions.
    ///
    /// - Note: Unlike Foundation Models,
    ///   AnyLanguageModel requires the `model` argument
    ///   and accepts any ``LanguageModel``.
    public convenience init(
        model: any LanguageModel,
        tools: [any Tool] = [],
        instructions: Instructions? = nil
    ) {
        self.init(model: model, tools: tools, instructions: instructions, transcript: Transcript())
    }

    /// Creates a session with a model and tools
    /// that continues from an existing transcript.
    ///
    /// - Note: Unlike Foundation Models,
    ///   AnyLanguageModel requires the `model` argument
    ///   and accepts any ``LanguageModel``.
    public convenience init(
        model: any LanguageModel,
        tools: [any Tool] = [],
        transcript: Transcript
    ) {
        self.init(model: model, tools: tools, instructions: nil, transcript: transcript)
    }

    /// Creates a session whose instructions and tools are resolved before each model request.
    ///
    /// The session evaluates the body of `dynamicInstructions`
    /// before every request to the model,
    /// including the request that continues a response after tool calls.
    /// The resolved instructions are sent with each request
    /// but never become part of the session's transcript.
    ///
    /// - Parameters:
    ///   - model: The language model to use.
    ///   - dynamicInstructions: The instructions and tools to resolve for each request.
    ///   - history: Earlier transcript entries to continue from.
    ///     Instructions entries in the history are left out,
    ///     because the dynamic instructions take their place.
    ///
    /// - Note: This API is exclusive to AnyLanguageModel on OS 26.
    ///   It follows the Foundation Models 27 `LanguageModelSession.init(model:dynamicInstructions:history:)` API,
    ///   so code that uses it ports to Foundation Models on OS 27.
    ///   Unlike Foundation Models, AnyLanguageModel requires the `model` argument.
    public convenience init(
        model: any LanguageModel,
        dynamicInstructions: sending some DynamicInstructions,
        history: some Collection<Transcript.Entry> = []
    ) {
        let history = history.filter { entry in
            if case .instructions = entry { return false }
            return true
        }
        self.init(
            model: model,
            tools: [],
            instructions: nil,
            transcript: Transcript(entries: history),
            dynamicInstructions: AnyDynamicInstructions(dynamicInstructions),
            dynamicProfile: nil
        )
    }

    /// Creates a session whose active model, instructions, Tools, and request
    /// projection are resolved before every model request.
    public convenience init(
        profile: sending some DynamicProfile,
        history: some Collection<Transcript.Entry> = []
    ) {
        let history = history.filter { entry in
            if case .instructions = entry { return false }
            return true
        }
        self.init(
            model: MissingDynamicProfileModel(),
            tools: [],
            instructions: nil,
            transcript: Transcript(entries: history),
            dynamicInstructions: nil,
            dynamicProfile: AnyDynamicProfile(profile)
        )
    }

    private init(
        model: any LanguageModel,
        tools: [any Tool],
        instructions: Instructions?,
        transcript: Transcript,
        dynamicInstructions: AnyDynamicInstructions? = nil,
        dynamicProfile: AnyDynamicProfile? = nil
    ) {
        self.model = model
        self.tools = tools
        self.dynamicInstructions = dynamicInstructions
        self.dynamicProfile = dynamicProfile
        let resolvedInstructions = instructions ?? Self.instructions(from: transcript)
        self.instructions = resolvedInstructions

        // Build transcript with instructions if provided and not already in transcript
        var finalTranscript = transcript
        if let instructions = resolvedInstructions {
            // Only add instructions if transcript doesn't already start with instructions
            let hasInstructions =
                finalTranscript.first.map { entry in
                    if case .instructions = entry { return true } else { return false }
                } ?? false

            if !hasInstructions {
                let instructionsEntry = Transcript.Entry.instructions(
                    Transcript.Instructions(
                        segments: [.text(.init(content: instructions.description))],
                        toolDefinitions:
                            tools
                            .filter(\.includesSchemaInInstructions)
                            .map { Transcript.ToolDefinition(tool: $0) }
                    )
                )
                finalTranscript.append(instructionsEntry)
            }
        }

        let state = Locked(State(finalTranscript))
        self.state = state
        self.properties = SessionPropertyValues(
            historyGetter: {
                state.withLock { locked in
                    locked.transcript.filter { entry in
                        if case .instructions = entry { return false }
                        return true
                    }
                }
            },
            historySetter: { history in
                state.withLock { locked in
                    let instructions = locked.transcript.prefix {
                        if case .instructions = $0 { return true }
                        return false
                    }
                    locked.transcript = Transcript(entries: Array(instructions) + history)
                }
            }
        )
    }

    private static func instructions(from transcript: Transcript) -> Instructions? {
        guard case .instructions(let instructions)? = transcript.first else { return nil }
        guard instructions.segments.count == 1,
            case .text(let text) = instructions.segments[0]
        else {
            return nil
        }
        return Instructions(content: text.content)
    }

    public func prewarm(promptPrefix: Prompt? = nil) {
        model.prewarm(for: self, promptPrefix: promptPrefix)
    }

    nonisolated private func recordUsage(_ usage: Usage) {
        guard usage != .zero else { return }
        withMutation(keyPath: \.usage) {
            state.withLock { $0.usage.add(usage) }
        }
    }

    nonisolated private func beginResponding() {
        withMutation(keyPath: \.isResponding) {
            state.withLock { $0.beginResponding() }
        }
    }

    nonisolated private func endResponding() {
        withMutation(keyPath: \.isResponding) {
            state.withLock { $0.endResponding() }
        }
    }

    // The prompt is the only entry committed before a request succeeds. Checkpoints and
    // the final response commit atomically at completion, so rollback owns only this ID.
    nonisolated private func removePrompt(id: String) {
        withMutation(keyPath: \.transcript) {
            state.withLock { state in
                state.transcript = Transcript(entries: state.transcript.filter { $0.id != id })
            }
        }
    }

    nonisolated private func wrapRespond<T>(_ operation: (String) async throws -> T) async throws -> T {
        let promptID = UUID().uuidString
        beginResponding()
        do {
            let result = try await operation(promptID)
            endResponding()
            return result
        } catch {
            let failure = error as? ProfiledModelFailure
            let policy =
                failure?.prepared.context.transcriptErrorHandlingPolicy
                ?? transcriptErrorHandlingPolicy
            if policy == .revertTranscript {
                removePrompt(id: promptID)
            }
            endResponding()
            throw failure?.underlyingError ?? error
        }
    }

    /// Returns the response with a `null` value for each omitted optional property
    /// when the response format's schema represents `nil` explicitly.
    nonisolated private static func representingNilExplicitly<Content>(
        in response: Response<Content>,
        responseFormat: Transcript.ResponseFormat?
    ) -> Response<Content> where Content: Generable {
        guard let responseFormat else { return response }
        let rawContent = responseFormat.schema.representingNilExplicitly(in: response.rawContent)
        guard rawContent != response.rawContent else { return response }
        return Response(
            // Schema-based responses return the generated content itself.
            content: (rawContent as? Content) ?? response.content,
            rawContent: rawContent,
            transcriptEntries: response.transcriptEntries,
            usage: response.usage,
            providerMetadata: response.providerMetadata
        )
    }

    nonisolated private func wrapStream<Content>(
        _ upstream: sending ResponseStream<Content>,
        promptEntry: Transcript.Entry,
        profileTracker: PreparedProfileRequestTracker? = nil
    ) -> ResponseStream<Content> where Content: Generable, Content.PartiallyGenerated: Sendable {
        let session = self
        let relay = AsyncThrowingStream<ResponseStream<Content>.Snapshot, any Error> { continuation in
            let stream = upstream
            let relayID = UUID()
            // Publish the task under the same lock used by completion removal, so a
            // fast relay cannot finish before registration and leave a stale handle.
            let task = session.responseRelays.withLock { relays in
                let task = Task {
                    defer { session.responseRelays.withLock { _ = $0.removeValue(forKey: relayID) } }
                    session.beginResponding()
                    var lastSnapshot: ResponseStream<Content>.Snapshot?
                    var accountedUsage = Usage.zero
                    var committedEntryIDs: Set<String> = []
                    do {
                        for try await snapshot in stream {
                            lastSnapshot = snapshot
                            session.recordUsage(snapshot.usage.increment(since: &accountedUsage))
                            continuation.yield(snapshot)
                        }

                        // AsyncThrowingStream may end normally when its task is cancelled.
                        // A partial snapshot must not become a completed transcript response.
                        try Task.checkCancellation()

                        // Commit the response to the transcript
                        // before the stream reports completion,
                        // so a caller that drains the stream
                        // and starts the next turn sees the full history.
                        guard let lastSnapshot else {
                            throw ResponseStreamError.noSnapshots
                        }
                        // Fill in `null` for omitted optional properties when the schema asks for it,
                        // and yield the result so that consumers and `collect()` see it.
                        var rawContent = lastSnapshot.rawContent
                        if case .prompt(let prompt) = promptEntry, let responseFormat = prompt.responseFormat {
                            rawContent = responseFormat.schema.representingNilExplicitly(in: rawContent)
                        }
                        if rawContent != lastSnapshot.rawContent {
                            continuation.yield(
                                ResponseStream<Content>.Snapshot(
                                    content: (try? Content.PartiallyGenerated(rawContent)) ?? lastSnapshot.content,
                                    rawContent: rawContent,
                                    transcriptEntries: lastSnapshot.transcriptEntries,
                                    usage: lastSnapshot.usage,
                                    providerMetadata: lastSnapshot.providerMetadata
                                )
                            )
                        }

                        // Extract text content from the generated content
                        let textContent: String
                        if case .string(let str) = rawContent.kind {
                            textContent = str
                        } else {
                            textContent = rawContent.jsonString
                        }

                        let responseEntry = Transcript.Entry.response(
                            Transcript.Response(
                                assetIDs: [],
                                segments: [.text(.init(content: textContent))],
                                providerMetadata: lastSnapshot.providerMetadata
                            )
                        )
                        session.withMutation(keyPath: \.transcript) {
                            session.state.withLock {
                                $0.transcript.append(contentsOf: lastSnapshot.transcriptEntries)
                                $0.transcript.append(responseEntry)
                            }
                        }
                        committedEntryIDs = Set(
                            lastSnapshot.transcriptEntries.map(\.id) + [responseEntry.id]
                        )
                        if let prepared = profileTracker?.prepared {
                            try await session.profileDidProduceEntries(
                                Array(lastSnapshot.transcriptEntries) + [responseEntry],
                                requestContext: prepared.context,
                                currentRoundEntries: []
                            )
                        }
                        session.endResponding()
                        continuation.finish()
                    } catch {
                        session.withMutation(keyPath: \.transcript) {
                            session.state.withLock { state in
                                if !committedEntryIDs.isEmpty {
                                    state.transcript = Transcript(
                                        entries: state.transcript.filter {
                                            !committedEntryIDs.contains($0.id)
                                        }
                                    )
                                }
                                let policy =
                                    profileTracker?.prepared?.context
                                    .transcriptErrorHandlingPolicy
                                    ?? state.transcriptErrorHandlingPolicy
                                if policy == .preserveTranscript {
                                    state.transcript.append(contentsOf: lastSnapshot?.transcriptEntries ?? [])
                                } else if policy == .revertTranscript {
                                    state.transcript = Transcript(
                                        entries: state.transcript.filter { $0.id != promptEntry.id }
                                    )
                                }
                            }
                        }
                        session.endResponding()
                        continuation.finish(throwing: error)
                    }
                }
                relays[relayID] = task
                return task
            }
            continuation.onTermination = { termination in
                if case .cancelled = termination {
                    task.cancel()
                }
            }
        }
        return ResponseStream(stream: relay)
    }

    /// Token usage reported by the model for a response.
    ///
    /// Matches the token-usage API in Foundation Models 27.
    /// Counts default to zero when the provider does not report them.
    /// Usage is cumulative across the response's tool rounds.
    ///
    /// - Note: This API is exclusive to AnyLanguageModel on OS 26.
    ///   It follows the Foundation Models 27 `Usage` API,
    ///   so code that uses it ports to Foundation Models on OS 27.
    ///   The `Codable` and `Equatable` conformances are exclusive to AnyLanguageModel;
    ///   Foundation Models 27 doesn't provide them.
    public struct Usage: Sendable, Equatable, Codable {
        /// Token counts for the input submitted to the model.
        public struct Input: Sendable, Equatable, Codable {
            /// The number of input tokens reported by the provider.
            public var totalTokenCount: Int

            /// The number of input tokens read from the provider's cache.
            public var cachedTokenCount: Int

            /// Creates input token counts.
            ///
            /// - Parameters:
            ///   - totalTokenCount: The reported input token count.
            ///   - cachedTokenCount: The reported count of input tokens read from cache.
            public init(totalTokenCount: Int, cachedTokenCount: Int) {
                self.totalTokenCount = totalTokenCount
                self.cachedTokenCount = cachedTokenCount
            }
        }

        /// Token counts for the output produced by the model.
        public struct Output: Sendable, Equatable, Codable {
            /// The number of output tokens reported by the provider.
            public var totalTokenCount: Int

            /// The number of reasoning tokens reported by the provider.
            public var reasoningTokenCount: Int

            /// Creates output token counts.
            ///
            /// - Parameters:
            ///   - totalTokenCount: The reported output token count.
            ///   - reasoningTokenCount: The reported reasoning token count.
            public init(totalTokenCount: Int, reasoningTokenCount: Int) {
                self.totalTokenCount = totalTokenCount
                self.reasoningTokenCount = reasoningTokenCount
            }
        }

        /// The token counts reported for the model's input.
        public var input: Input

        /// The token counts reported for the model's output.
        public var output: Output

        /// Additional usage statistics supplied by the model.
        public var metadata: [String: GeneratedContent]

        /// The sum of the input and output token counts.
        public var totalTokenCount: Int {
            input.totalTokenCount + output.totalTokenCount
        }

        /// Creates usage from input and output token counts.
        ///
        /// - Parameters:
        ///   - input: The input token counts.
        ///   - output: The output token counts.
        ///   - metadata: Additional usage statistics,
        ///     converted to generated content for storage.
        public init(
            input: Input,
            output: Output,
            metadata: [String: any ConvertibleToGeneratedContent] = [:]
        ) {
            self.input = input
            self.output = output
            self.metadata = metadata.mapValues { $0.generatedContent }
        }

        static let zero = Self(
            input: .init(totalTokenCount: 0, cachedTokenCount: 0),
            output: .init(totalTokenCount: 0, reasoningTokenCount: 0)
        )

        /// Accumulates counts across responses;
        /// the latest value wins for each metadata key.
        mutating func add(_ other: Self) {
            input.totalTokenCount += other.input.totalTokenCount
            input.cachedTokenCount += other.input.cachedTokenCount
            output.totalTokenCount += other.output.totalTokenCount
            output.reasoningTokenCount += other.output.reasoningTokenCount
            metadata.merge(other.metadata) { _, latest in latest }
        }

        /// Returns counts not yet accounted for in this stream,
        /// retaining the highest reported count for each field
        /// and returning only new or changed metadata keys.
        func increment(since previous: inout Self) -> Self {
            func increase(_ count: Int, _ highest: inout Int) -> Int {
                let delta = max(0, count - highest)
                highest = max(highest, count)
                return delta
            }
            let changedMetadata = metadata.filter { previous.metadata[$0.key] != $0.value }
            previous.metadata.merge(changedMetadata) { _, latest in latest }
            return Self(
                input: .init(
                    totalTokenCount: increase(input.totalTokenCount, &previous.input.totalTokenCount),
                    cachedTokenCount: increase(input.cachedTokenCount, &previous.input.cachedTokenCount)
                ),
                output: .init(
                    totalTokenCount: increase(output.totalTokenCount, &previous.output.totalTokenCount),
                    reasoningTokenCount: increase(output.reasoningTokenCount, &previous.output.reasoningTokenCount)
                ),
                metadata: changedMetadata
            )
        }
    }

    /// A model response containing generated content and associated metadata.
    public struct Response<Content>: Sendable where Content: Generable, Content: Sendable {
        /// The decoded response content.
        public let content: Content

        /// The raw content produced by the model.
        public let rawContent: GeneratedContent

        /// The transcript entries associated with the response.
        public let transcriptEntries: ArraySlice<Transcript.Entry>

        /// Provider-reported token usage,
        /// with zero counts for values the provider does not report.
        ///
        /// - Note: This property is exclusive to AnyLanguageModel on OS 26.
        ///   It follows the Foundation Models 27 `Response.usage` API,
        ///   so code that uses it ports to Foundation Models on OS 27.
        public let usage: Usage

        internal let providerMetadata: [String: String]?

        /// Creates a response value from generated content and transcript entries.
        /// - Parameters:
        ///   - content: The decoded response content.
        ///   - rawContent: The raw content produced by the model.
        ///   - transcriptEntries: Transcript entries associated with the response.
        ///   - usage: Provider-reported token usage.
        ///
        /// - Note: This initializer is exclusive to AnyLanguageModel.
        ///   It's public so that language models outside this module
        ///   can create responses;
        ///   Foundation Models doesn't make it public.
        public init(
            content: Content,
            rawContent: GeneratedContent,
            transcriptEntries: ArraySlice<Transcript.Entry>,
            usage: Usage = .init(
                input: .init(totalTokenCount: 0, cachedTokenCount: 0),
                output: .init(totalTokenCount: 0, reasoningTokenCount: 0)
            )
        ) {
            self.init(
                content: content,
                rawContent: rawContent,
                transcriptEntries: transcriptEntries,
                usage: usage,
                providerMetadata: nil
            )
        }

        internal init(
            content: Content,
            rawContent: GeneratedContent,
            transcriptEntries: ArraySlice<Transcript.Entry>,
            usage: Usage = .init(
                input: .init(totalTokenCount: 0, cachedTokenCount: 0),
                output: .init(totalTokenCount: 0, reasoningTokenCount: 0)
            ),
            providerMetadata: [String: String]?
        ) {
            self.content = content
            self.rawContent = rawContent
            self.transcriptEntries = transcriptEntries
            self.usage = usage
            self.providerMetadata = providerMetadata
        }
    }

    @discardableResult
    nonisolated public func respond<Content>(
        to prompt: Prompt,
        generating type: Content.Type = Content.self,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) async throws -> Response<Content> where Content: Generable {
        try await respond(
            to: prompt,
            responseFormat: type == String.self ? nil : .init(type: type),
            options: options
        ) {
            try await profiledResponse(options: options) { model, resolvedOptions, contextOptions in
                try await model.respond(
                    within: self,
                    to: prompt,
                    generating: type,
                    includeSchemaInPrompt: contextOptions.includeSchemaInPrompt
                        ?? includeSchemaInPrompt,
                    options: resolvedOptions
                )
            }
        }
    }

    nonisolated private func profiledResponse<Content>(
        options: GenerationOptions,
        generate: (
            any LanguageModel,
            GenerationOptions,
            ContextOptions
        ) async throws -> Response<Content>
    ) async throws -> ProfiledModelResponse<Content> where Content: Generable {
        guard dynamicProfile != nil else {
            return ProfiledModelResponse(
                response: try await generate(model, options, .init()),
                prepared: nil
            )
        }
        let context = try await resolvedRequestContext(including: [], options: options)
        let prepared = PreparedProfileRequest(
            session: self,
            context: context,
            callSiteOptions: options
        )
        do {
            let response = try await ProfileRequestBinding.$prepared.withValue(prepared) {
                try await generate(context.model, context.options, context.contextOptions)
            }
            return ProfiledModelResponse(response: response, prepared: prepared)
        } catch {
            throw ProfiledModelFailure(underlyingError: error, prepared: prepared)
        }
    }

    nonisolated private func respond<Content: Generable>(
        to prompt: Prompt,
        responseFormat: Transcript.ResponseFormat?,
        options: GenerationOptions,
        generate: () async throws -> ProfiledModelResponse<Content>
    ) async throws -> Response<Content> {
        try await wrapRespond { promptID in
            // Add prompt to transcript
            let promptEntry = Transcript.Entry.prompt(
                Transcript.Prompt(
                    id: promptID,
                    segments: try prompt.makeTranscriptSegments(),
                    options: options,
                    responseFormat: responseFormat
                )
            )
            withMutation(keyPath: \.transcript) {
                state.withLock { $0.transcript.append(promptEntry) }
            }

            let profiled = try await generate()
            let response = Self.representingNilExplicitly(
                in: profiled.response,
                responseFormat: responseFormat
            )

            recordUsage(response.usage)

            // Add response entry to transcript
            let textContent: String
            if case .string(let str) = response.rawContent.kind {
                textContent = str
            } else {
                textContent = response.rawContent.jsonString
            }

            let responseEntry = Transcript.Entry.response(
                Transcript.Response(
                    assetIDs: [],
                    segments: [.text(.init(content: textContent))],
                    providerMetadata: response.providerMetadata
                )
            )

            try await commitResponse(
                response,
                entry: responseEntry,
                prepared: profiled.prepared
            )

            return response
        }
    }

    nonisolated private func commitResponse<Content>(
        _ response: Response<Content>,
        entry responseEntry: Transcript.Entry,
        prepared: PreparedProfileRequest?
    ) async throws where Content: Generable {
        withMutation(keyPath: \.transcript) {
            state.withLock { lockedState in
                lockedState.transcript.append(contentsOf: response.transcriptEntries)
                lockedState.transcript.append(responseEntry)
            }
        }

        guard let prepared else { return }
        do {
            try await profileDidProduceEntries(
                Array(response.transcriptEntries) + [responseEntry],
                requestContext: prepared.context,
                currentRoundEntries: []
            )
        } catch {
            let ids = Set(response.transcriptEntries.map(\.id) + [responseEntry.id])
            withMutation(keyPath: \.transcript) {
                state.withLock { lockedState in
                    lockedState.transcript = Transcript(
                        entries: lockedState.transcript.filter { !ids.contains($0.id) }
                    )
                }
            }
            throw ProfiledModelFailure(underlyingError: error, prepared: prepared)
        }
    }

    nonisolated public func streamResponse<Content>(
        to prompt: Prompt,
        generating type: Content.Type = Content.self,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) -> sending ResponseStream<Content> where Content: Generable {
        // Add prompt to transcript
        let segments: [Transcript.Segment]
        do { segments = try prompt.makeTranscriptSegments() } catch {
            return ResponseStream(stream: AsyncThrowingStream { $0.finish(throwing: error) })
        }
        let promptEntry = Transcript.Entry.prompt(
            Transcript.Prompt(
                segments: segments,
                options: options,
                responseFormat: type == String.self ? nil : .init(type: type)
            )
        )
        withMutation(keyPath: \.transcript) {
            state.withLock { $0.transcript.append(promptEntry) }
        }

        let upstream: ResponseStream<Content>
        let profileTracker: PreparedProfileRequestTracker?
        if dynamicProfile != nil {
            let tracker = PreparedProfileRequestTracker()
            profileTracker = tracker
            upstream = profileDispatchedStream(
                prompt: prompt,
                type: type,
                includeSchemaInPrompt: includeSchemaInPrompt,
                options: options,
                tracker: tracker
            )
        } else {
            profileTracker = nil
            upstream = model.streamResponse(
                within: self,
                to: prompt,
                generating: type,
                includeSchemaInPrompt: includeSchemaInPrompt,
                options: options
            )
        }
        return wrapStream(
            upstream,
            promptEntry: promptEntry,
            profileTracker: profileTracker
        )
    }

    nonisolated private func profileDispatchedStream<Content>(
        prompt: Prompt,
        type: Content.Type,
        includeSchemaInPrompt: Bool,
        options: GenerationOptions,
        tracker: PreparedProfileRequestTracker
    ) -> ResponseStream<Content> where Content: Generable {
        profileDispatchedStream(options: options, tracker: tracker) {
            model,
            resolvedOptions,
            contextOptions in
            model.streamResponse(
                within: self,
                to: prompt,
                generating: type,
                includeSchemaInPrompt: contextOptions.includeSchemaInPrompt
                    ?? includeSchemaInPrompt,
                options: resolvedOptions
            )
        }
    }

    nonisolated private func profileDispatchedStream<Content>(
        options: GenerationOptions,
        tracker: PreparedProfileRequestTracker,
        generate:
            @Sendable @escaping (
                any LanguageModel,
                GenerationOptions,
                ContextOptions
            ) -> ResponseStream<Content>
    ) -> ResponseStream<Content> where Content: Generable {
        let stream = AsyncThrowingStream<ResponseStream<Content>.Snapshot, any Error> { continuation in
            let task = Task {
                do {
                    let context = try await self.resolvedRequestContext(including: [], options: options)
                    let prepared = PreparedProfileRequest(
                        session: self,
                        context: context,
                        callSiteOptions: options
                    )
                    tracker.prepared = prepared
                    let upstream = ProfileRequestBinding.$prepared.withValue(prepared) {
                        generate(context.model, context.options, context.contextOptions)
                    }
                    for try await snapshot in upstream {
                        continuation.yield(snapshot)
                    }
                    continuation.finish()
                } catch {
                    continuation.finish(throwing: error)
                }
            }
            continuation.onTermination = { _ in task.cancel() }
        }
        return ResponseStream(stream: stream)
    }
}

// MARK: - String Response Convenience Methods

extension LanguageModelSession {
    @discardableResult
    nonisolated public func respond(
        to prompt: Prompt,
        options: GenerationOptions = GenerationOptions()
    ) async throws -> Response<String> {
        try await respond(
            to: prompt,
            generating: String.self,
            includeSchemaInPrompt: true,
            options: options
        )
    }

    @discardableResult
    nonisolated public func respond(
        to prompt: String,
        options: GenerationOptions = GenerationOptions()
    ) async throws -> Response<String> {
        try await respond(to: Prompt(prompt), options: options)
    }

    @discardableResult
    nonisolated public func respond(
        options: GenerationOptions = GenerationOptions(),
        @PromptBuilder prompt: () throws -> Prompt
    ) async throws -> Response<String> {
        try await respond(to: try prompt(), options: options)
    }

    public func streamResponse(
        to prompt: Prompt,
        options: GenerationOptions = GenerationOptions()
    ) -> sending ResponseStream<String> {
        streamResponse(
            to: prompt,
            generating: String.self,
            includeSchemaInPrompt: true,
            options: options
        )
    }

    public func streamResponse(
        to prompt: String,
        options: GenerationOptions = GenerationOptions()
    ) -> sending ResponseStream<String> {
        streamResponse(to: Prompt(prompt), options: options)
    }

    public func streamResponse(
        options: GenerationOptions = GenerationOptions(),
        @PromptBuilder prompt: () throws -> Prompt
    ) rethrows -> sending ResponseStream<String> {
        streamResponse(to: try prompt(), options: options)
    }
}

// MARK: - GeneratedContent with Schema Convenience Methods

extension LanguageModelSession {
    /// Generates content that conforms to the supplied schema.
    /// Provider restrictions still apply; OpenAI strict mode requires an object root.
    @discardableResult
    nonisolated public func respond(
        to prompt: Prompt,
        schema: GenerationSchema,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) async throws -> Response<GeneratedContent> {
        try await respond(to: prompt, responseFormat: .init(schema: schema), options: options) {
            try await profiledResponse(options: options) { model, resolvedOptions, contextOptions in
                try await model.respond(
                    within: self,
                    to: prompt,
                    schema: schema,
                    includeSchemaInPrompt: contextOptions.includeSchemaInPrompt
                        ?? includeSchemaInPrompt,
                    options: resolvedOptions
                )
            }
        }
    }

    /// Generates content that conforms to the supplied schema.
    /// Provider restrictions still apply; OpenAI strict mode requires an object root.
    @discardableResult
    nonisolated public func respond(
        to prompt: String,
        schema: GenerationSchema,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) async throws -> Response<GeneratedContent> {
        try await respond(
            to: Prompt(prompt),
            schema: schema,
            includeSchemaInPrompt: includeSchemaInPrompt,
            options: options
        )
    }

    /// Generates content that conforms to the supplied schema.
    /// Provider restrictions still apply; OpenAI strict mode requires an object root.
    @discardableResult
    nonisolated public func respond(
        schema: GenerationSchema,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions(),
        @PromptBuilder prompt: () throws -> Prompt
    ) async throws -> Response<GeneratedContent> {
        try await respond(
            to: try prompt(),
            schema: schema,
            includeSchemaInPrompt: includeSchemaInPrompt,
            options: options
        )
    }

    /// Streams content that conforms to the supplied schema.
    /// Provider restrictions still apply; OpenAI strict mode requires an object root.
    nonisolated public func streamResponse(
        to prompt: Prompt,
        schema: GenerationSchema,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) -> sending ResponseStream<GeneratedContent> {
        let segments: [Transcript.Segment]
        do { segments = try prompt.makeTranscriptSegments() } catch {
            return ResponseStream(stream: AsyncThrowingStream { $0.finish(throwing: error) })
        }
        let promptEntry = Transcript.Entry.prompt(
            Transcript.Prompt(
                segments: segments,
                options: options,
                responseFormat: .init(schema: schema)
            )
        )
        withMutation(keyPath: \.transcript) {
            state.withLock { $0.transcript.append(promptEntry) }
        }

        let upstream: ResponseStream<GeneratedContent>
        let profileTracker: PreparedProfileRequestTracker?
        if dynamicProfile != nil {
            let tracker = PreparedProfileRequestTracker()
            profileTracker = tracker
            upstream = profileDispatchedStream(options: options, tracker: tracker) {
                model,
                resolvedOptions,
                contextOptions in
                model.streamResponse(
                    within: self,
                    to: prompt,
                    schema: schema,
                    includeSchemaInPrompt: contextOptions.includeSchemaInPrompt
                        ?? includeSchemaInPrompt,
                    options: resolvedOptions
                )
            }
        } else {
            profileTracker = nil
            upstream = model.streamResponse(
                within: self,
                to: prompt,
                schema: schema,
                includeSchemaInPrompt: includeSchemaInPrompt,
                options: options
            )
        }
        return wrapStream(
            upstream,
            promptEntry: promptEntry,
            profileTracker: profileTracker
        )
    }

    /// Streams content that conforms to the supplied schema.
    /// Provider restrictions still apply; OpenAI strict mode requires an object root.
    nonisolated public func streamResponse(
        to prompt: String,
        schema: GenerationSchema,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) -> sending ResponseStream<GeneratedContent> {
        streamResponse(
            to: Prompt(prompt),
            schema: schema,
            includeSchemaInPrompt: includeSchemaInPrompt,
            options: options
        )
    }

    /// Streams content that conforms to the supplied schema.
    /// Provider restrictions still apply; OpenAI strict mode requires an object root.
    nonisolated public func streamResponse(
        schema: GenerationSchema,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions(),
        @PromptBuilder prompt: () throws -> Prompt
    ) rethrows -> sending ResponseStream<GeneratedContent> {
        streamResponse(to: try prompt(), schema: schema, includeSchemaInPrompt: includeSchemaInPrompt, options: options)
    }
}

// MARK: - Generic Content Convenience Methods

extension LanguageModelSession {
    @discardableResult
    nonisolated public func respond<Content>(
        to prompt: String,
        generating type: Content.Type = Content.self,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) async throws -> Response<Content> where Content: Generable {
        try await respond(
            to: Prompt(prompt),
            generating: type,
            includeSchemaInPrompt: includeSchemaInPrompt,
            options: options
        )
    }

    @discardableResult
    nonisolated public func respond<Content>(
        generating type: Content.Type = Content.self,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions(),
        @PromptBuilder prompt: () throws -> Prompt
    ) async throws -> Response<Content> where Content: Generable {
        try await respond(
            to: try prompt(),
            generating: type,
            includeSchemaInPrompt: includeSchemaInPrompt,
            options: options
        )
    }

    nonisolated public func streamResponse<Content>(
        to prompt: String,
        generating type: Content.Type = Content.self,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) -> sending ResponseStream<Content> where Content: Generable {
        streamResponse(
            to: Prompt(prompt),
            generating: type,
            includeSchemaInPrompt: includeSchemaInPrompt,
            options: options
        )
    }

    public func streamResponse<Content>(
        generating type: Content.Type = Content.self,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions(),
        @PromptBuilder prompt: () throws -> Prompt
    ) rethrows -> sending ResponseStream<Content> where Content: Generable {
        streamResponse(
            to: try prompt(),
            generating: type,
            includeSchemaInPrompt: includeSchemaInPrompt,
            options: options
        )
    }
}

// MARK: - Image Convenience Methods

extension LanguageModelSession {
    /// Produces a text response to a prompt and an image.
    ///
    /// - Note: This API is exclusive to AnyLanguageModel
    ///   and will change to match Foundation Models 27 prompt attachments
    ///   in AnyLanguageModel 2.0.
    @discardableResult
    nonisolated public func respond(
        to prompt: String,
        image: Transcript.ImageSegment,
        options: GenerationOptions = GenerationOptions()
    ) async throws -> Response<String> {
        try await respond(
            to: prompt,
            images: [image],
            options: options
        )
    }

    /// Produces a text response to a prompt and images.
    ///
    /// - Note: This API is exclusive to AnyLanguageModel
    ///   and will change to match Foundation Models 27 prompt attachments
    ///   in AnyLanguageModel 2.0.
    @discardableResult
    nonisolated public func respond(
        to prompt: String,
        images: [Transcript.ImageSegment],
        options: GenerationOptions = GenerationOptions()
    ) async throws -> Response<String> {
        try await respond(
            to: prompt,
            images: images,
            generating: String.self,
            includeSchemaInPrompt: true,
            options: options
        )
    }

    /// Produces a response of the specified type to a prompt and an image.
    ///
    /// - Note: This API is exclusive to AnyLanguageModel
    ///   and will change to match Foundation Models 27 prompt attachments
    ///   in AnyLanguageModel 2.0.
    @discardableResult
    nonisolated public func respond<Content>(
        to prompt: String,
        image: Transcript.ImageSegment,
        generating type: Content.Type = Content.self,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) async throws -> Response<Content> where Content: Generable {
        try await respond(
            to: prompt,
            images: [image],
            generating: type,
            includeSchemaInPrompt: includeSchemaInPrompt,
            options: options
        )
    }

    /// Produces a response of the specified type to a prompt and images.
    ///
    /// - Note: This API is exclusive to AnyLanguageModel
    ///   and will change to match Foundation Models 27 prompt attachments
    ///   in AnyLanguageModel 2.0.
    @discardableResult
    nonisolated public func respond<Content>(
        to prompt: String,
        images: [Transcript.ImageSegment],
        generating type: Content.Type = Content.self,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) async throws -> Response<Content> where Content: Generable {
        try await wrapRespond { promptID in
            // Build segments from text and images
            var segments: [Transcript.Segment] = []
            if !prompt.isEmpty {
                segments.append(.text(.init(content: prompt)))
            }
            segments.append(contentsOf: images.map { .image($0) })

            // Add prompt to transcript
            let promptEntry = Transcript.Entry.prompt(
                Transcript.Prompt(
                    id: promptID,
                    segments: segments,
                    options: options,
                    responseFormat: type == String.self ? nil : .init(type: type)
                )
            )
            withMutation(keyPath: \.transcript) {
                state.withLock { $0.transcript.append(promptEntry) }
            }

            // Extract text content for the Prompt parameter
            let textPrompt = Prompt(prompt)

            let profiled = try await profiledResponse(options: options) {
                model,
                resolvedOptions,
                contextOptions in
                try await model.respond(
                    within: self,
                    to: textPrompt,
                    generating: type,
                    includeSchemaInPrompt: contextOptions.includeSchemaInPrompt
                        ?? includeSchemaInPrompt,
                    options: resolvedOptions
                )
            }
            let response = Self.representingNilExplicitly(
                in: profiled.response,
                responseFormat: type == String.self ? nil : .init(type: type)
            )

            recordUsage(response.usage)

            // Add response entry to transcript
            let textContent: String
            if case .string(let str) = response.rawContent.kind {
                textContent = str
            } else {
                textContent = response.rawContent.jsonString
            }

            let responseEntry = Transcript.Entry.response(
                Transcript.Response(
                    assetIDs: [],
                    segments: [.text(.init(content: textContent))],
                    providerMetadata: response.providerMetadata
                )
            )

            try await commitResponse(
                response,
                entry: responseEntry,
                prepared: profiled.prepared
            )

            return response
        }
    }

    /// Streams a text response to a prompt and an image.
    ///
    /// - Note: This API is exclusive to AnyLanguageModel
    ///   and will change to match Foundation Models 27 prompt attachments
    ///   in AnyLanguageModel 2.0.
    public func streamResponse(
        to prompt: String,
        image: Transcript.ImageSegment,
        options: GenerationOptions = GenerationOptions()
    ) -> sending ResponseStream<String> {
        streamResponse(
            to: prompt,
            images: [image],
            options: options
        )
    }

    /// Streams a text response to a prompt and images.
    ///
    /// - Note: This API is exclusive to AnyLanguageModel
    ///   and will change to match Foundation Models 27 prompt attachments
    ///   in AnyLanguageModel 2.0.
    public func streamResponse(
        to prompt: String,
        images: [Transcript.ImageSegment],
        options: GenerationOptions = GenerationOptions()
    ) -> sending ResponseStream<String> {
        streamResponse(
            to: prompt,
            images: images,
            generating: String.self,
            includeSchemaInPrompt: true,
            options: options
        )
    }

    /// Streams a response of the specified type to a prompt and an image.
    ///
    /// - Note: This API is exclusive to AnyLanguageModel
    ///   and will change to match Foundation Models 27 prompt attachments
    ///   in AnyLanguageModel 2.0.
    nonisolated public func streamResponse<Content>(
        to prompt: String,
        image: Transcript.ImageSegment,
        generating type: Content.Type = Content.self,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) -> sending ResponseStream<Content> where Content: Generable {
        streamResponse(
            to: prompt,
            images: [image],
            generating: type,
            includeSchemaInPrompt: includeSchemaInPrompt,
            options: options
        )
    }

    /// Streams a response of the specified type to a prompt and images.
    ///
    /// - Note: This API is exclusive to AnyLanguageModel
    ///   and will change to match Foundation Models 27 prompt attachments
    ///   in AnyLanguageModel 2.0.
    nonisolated public func streamResponse<Content>(
        to prompt: String,
        images: [Transcript.ImageSegment],
        generating type: Content.Type = Content.self,
        includeSchemaInPrompt: Bool = true,
        options: GenerationOptions = GenerationOptions()
    ) -> sending ResponseStream<Content> where Content: Generable {
        // Build segments from text and images
        var segments: [Transcript.Segment] = []
        if !prompt.isEmpty {
            segments.append(.text(.init(content: prompt)))
        }
        segments.append(contentsOf: images.map { .image($0) })

        // Create prompt entry that will be added when stream starts
        let promptEntry = Transcript.Entry.prompt(
            Transcript.Prompt(
                segments: segments,
                options: options,
                responseFormat: type == String.self ? nil : .init(type: type)
            )
        )
        withMutation(keyPath: \.transcript) {
            state.withLock { $0.transcript.append(promptEntry) }
        }

        // Extract text content for the Prompt parameter
        let textPrompt = Prompt(prompt)

        let upstream: ResponseStream<Content>
        let profileTracker: PreparedProfileRequestTracker?
        if dynamicProfile != nil {
            let tracker = PreparedProfileRequestTracker()
            profileTracker = tracker
            upstream = profileDispatchedStream(options: options, tracker: tracker) {
                model,
                resolvedOptions,
                contextOptions in
                model.streamResponse(
                    within: self,
                    to: textPrompt,
                    generating: type,
                    includeSchemaInPrompt: contextOptions.includeSchemaInPrompt
                        ?? includeSchemaInPrompt,
                    options: resolvedOptions
                )
            }
        } else {
            profileTracker = nil
            upstream = model.streamResponse(
                within: self,
                to: textPrompt,
                generating: type,
                includeSchemaInPrompt: includeSchemaInPrompt,
                options: options
            )
        }
        return wrapStream(
            upstream,
            promptEntry: promptEntry,
            profileTracker: profileTracker
        )
    }
}

// MARK: -

extension LanguageModelSession {
    @discardableResult
    public func logFeedbackAttachment(
        sentiment: LanguageModelFeedback.Sentiment?,
        issues: [LanguageModelFeedback.Issue] = [],
        desiredOutput: Transcript.Entry? = nil
    ) -> Data {
        model.logFeedbackAttachment(
            within: self,
            sentiment: sentiment,
            issues: issues,
            desiredOutput: desiredOutput
        )
    }

    /// Logs feedback about the most recent response, with the text you wanted instead.
    ///
    /// - Parameters:
    ///   - sentiment: Whether the response was positive, negative, or neutral.
    ///   - issues: The problems with the response.
    ///   - desiredResponseText: The text that the model should have generated.
    /// - Returns: The feedback attachment data.
    @discardableResult
    public func logFeedbackAttachment(
        sentiment: LanguageModelFeedback.Sentiment?,
        issues: [LanguageModelFeedback.Issue] = [],
        desiredResponseText: String?
    ) -> Data {
        let entry = desiredResponseText.map { content in
            Transcript.Entry.response(
                Transcript.Response(assetIDs: [], segments: [.text(.init(content: content))])
            )
        }
        return logFeedbackAttachment(sentiment: sentiment, issues: issues, desiredOutput: entry)
    }

    /// Logs feedback about the most recent response, with the content you wanted instead.
    ///
    /// - Parameters:
    ///   - sentiment: Whether the response was positive, negative, or neutral.
    ///   - issues: The problems with the response.
    ///   - desiredResponseContent: The content that the model should have generated.
    /// - Returns: The feedback attachment data.
    @discardableResult
    public func logFeedbackAttachment(
        sentiment: LanguageModelFeedback.Sentiment?,
        issues: [LanguageModelFeedback.Issue] = [],
        desiredResponseContent: (any ConvertibleToGeneratedContent)?
    ) -> Data {
        let entry = desiredResponseContent.map { content in
            let segment = Transcript.StructuredSegment(
                source: String(describing: type(of: content)),
                content: content.generatedContent
            )
            return Transcript.Entry.response(
                Transcript.Response(assetIDs: [], segments: [.structure(segment)])
            )
        }
        return logFeedbackAttachment(sentiment: sentiment, issues: issues, desiredOutput: entry)
    }
}

// MARK: -

extension LanguageModelSession {
    public enum GenerationError: Error, LocalizedError {
        public struct Context: Sendable {
            public let debugDescription: String

            public init(debugDescription: String) {
                self.debugDescription = debugDescription
            }
        }

        public struct Refusal: Sendable {
            /// The transcript entries associated with the refusal.
            ///
            /// - Note: This property is exclusive to AnyLanguageModel
            ///   and using it means your code is no longer drop-in compatible
            ///   with the Foundation Models framework.
            ///   Foundation Models takes transcript entries in the initializer
            ///   but doesn't make this property public.
            public let transcriptEntries: [Transcript.Entry]

            public init(transcriptEntries: [Transcript.Entry]) {
                self.transcriptEntries = transcriptEntries
            }

            public var explanation: Response<String> {
                get async throws {
                    // Extract explanation from transcript entries
                    let explanationText = transcriptEntries.compactMap { entry in
                        if case .response(let response) = entry {
                            return response.segments.compactMap { segment in
                                if case .text(let textSegment) = segment {
                                    return textSegment.content
                                }
                                return nil
                            }.joined(separator: " ")
                        }
                        return nil
                    }.joined(separator: "\n")

                    return Response(
                        content: explanationText.isEmpty ? "No explanation available" : explanationText,
                        rawContent: GeneratedContent(
                            explanationText.isEmpty ? "No explanation available" : explanationText
                        ),
                        transcriptEntries: ArraySlice(transcriptEntries)
                    )
                }
            }

            public var explanationStream: ResponseStream<String> {
                // Create a simple stream that yields the explanation text
                let explanationText = transcriptEntries.compactMap { entry in
                    if case .response(let response) = entry {
                        return response.segments.compactMap { segment in
                            if case .text(let textSegment) = segment {
                                return textSegment.content
                            }
                            return nil
                        }.joined(separator: " ")
                    }
                    return nil
                }.joined(separator: "\n")

                let finalText = explanationText.isEmpty ? "No explanation available" : explanationText
                return ResponseStream(content: finalText, rawContent: GeneratedContent(finalText))
            }
        }

        case exceededContextWindowSize(Context)
        case assetsUnavailable(Context)
        case guardrailViolation(Context)
        case unsupportedGuide(Context)
        case unsupportedLanguageOrLocale(Context)
        case decodingFailure(Context)
        case rateLimited(Context)
        case concurrentRequests(Context)
        case refusal(Refusal, Context)

        public var errorDescription: String? { nil }
        public var recoverySuggestion: String? { nil }
        public var failureReason: String? { nil }
    }

    public struct ToolCallError: Error, LocalizedError {
        public var tool: any Tool
        public var underlyingError: any Error

        public init(tool: any Tool, underlyingError: any Error) {
            self.tool = tool
            self.underlyingError = underlyingError
        }

        public var errorDescription: String? { nil }
    }
}

extension LanguageModelSession {
    /// An asynchronous sequence of snapshots of a model response.
    public struct ResponseStream<Content>: Sendable where Content: Generable, Content.PartiallyGenerated: Sendable {
        private let fallbackSnapshot: Snapshot?
        private let streaming: AsyncThrowingStream<Snapshot, any Error>?

        /// Creates a response stream that yields a single snapshot.
        /// - Parameters:
        ///   - content: The complete response content.
        ///   - rawContent: The raw content produced by the model.
        ///   - usage: Provider-reported token usage.
        ///
        /// - Note: This initializer is exclusive to AnyLanguageModel.
        ///   It's public so that language models outside this module
        ///   can create response streams;
        ///   Foundation Models doesn't make it public.
        public init(
            content: Content,
            rawContent: GeneratedContent,
            usage: Usage = .init(
                input: .init(totalTokenCount: 0, cachedTokenCount: 0),
                output: .init(totalTokenCount: 0, reasoningTokenCount: 0)
            )
        ) {
            self.fallbackSnapshot = Snapshot(
                content: content.asPartiallyGenerated(),
                rawContent: rawContent,
                usage: usage
            )
            self.streaming = nil
        }

        /// Creates a response stream that yields snapshots from an async stream.
        /// - Parameter stream: The snapshot stream to relay.
        ///
        /// - Note: This initializer is exclusive to AnyLanguageModel.
        ///   It's public so that language models outside this module
        ///   can create response streams;
        ///   Foundation Models doesn't make it public.
        public init(stream: AsyncThrowingStream<Snapshot, any Error>) {
            // When streaming, snapshots arrive from the upstream sequence, so no fallback is required.
            self.fallbackSnapshot = nil
            self.streaming = stream
        }

        /// A snapshot of partially generated content and response metadata.
        public struct Snapshot: Sendable where Content.PartiallyGenerated: Sendable {
            /// The partially generated response content.
            public var content: Content.PartiallyGenerated

            /// The raw content produced so far by the model.
            public var rawContent: GeneratedContent

            /// Transcript entries (reasoning, tool calls and outputs) produced so far while streaming.
            /// Cumulative across tool rounds;
            /// empty for providers that don't stream reasoning or tool activity.
            ///
            /// - Note: This property is exclusive to AnyLanguageModel on OS 26.
            ///   It follows the Foundation Models 27 `ResponseStream.Snapshot.transcriptEntries` API,
            ///   so code that uses it ports to Foundation Models on OS 27.
            public var transcriptEntries: ArraySlice<Transcript.Entry>

            /// Provider-reported counts so far,
            /// with zero counts for values the provider does not report.
            ///
            /// - Note: This property is exclusive to AnyLanguageModel on OS 26.
            ///   It follows the Foundation Models 27 `ResponseStream.Snapshot.usage` API,
            ///   so code that uses it ports to Foundation Models on OS 27.
            public var usage: Usage

            internal var providerMetadata: [String: String]?

            /// Creates a snapshot from partially generated content and raw content.
            /// - Parameters:
            ///   - content: The partially generated content.
            ///   - rawContent: The raw content produced by the model.
            ///   - transcriptEntries: Transcript entries accumulated so far (reasoning/tool calls/outputs).
            ///   - usage: Provider-reported token usage so far.
            ///
            /// - Note: This initializer is exclusive to AnyLanguageModel.
            ///   It's public so that language models outside this module
            ///   can create snapshots;
            ///   Foundation Models doesn't make it public.
            public init(
                content: Content.PartiallyGenerated,
                rawContent: GeneratedContent,
                transcriptEntries: ArraySlice<Transcript.Entry> = [],
                usage: Usage = .init(
                    input: .init(totalTokenCount: 0, cachedTokenCount: 0),
                    output: .init(totalTokenCount: 0, reasoningTokenCount: 0)
                )
            ) {
                self.init(
                    content: content,
                    rawContent: rawContent,
                    transcriptEntries: transcriptEntries,
                    usage: usage,
                    providerMetadata: nil
                )
            }

            internal init(
                content: Content.PartiallyGenerated,
                rawContent: GeneratedContent,
                transcriptEntries: ArraySlice<Transcript.Entry> = [],
                usage: Usage = .init(
                    input: .init(totalTokenCount: 0, cachedTokenCount: 0),
                    output: .init(totalTokenCount: 0, reasoningTokenCount: 0)
                ),
                providerMetadata: [String: String]?
            ) {
                self.content = content
                self.rawContent = rawContent
                self.transcriptEntries = transcriptEntries
                self.usage = usage
                self.providerMetadata = providerMetadata
            }
        }
    }
}

extension LanguageModelSession.ResponseStream: AsyncSequence {
    public typealias Element = Snapshot

    public struct AsyncIterator: AsyncIteratorProtocol {
        private var hasYielded = false
        private let fallbackSnapshot: Snapshot?
        private var streamIterator: AsyncThrowingStream<Snapshot, any Error>.AsyncIterator?
        private let useStream: Bool

        init(fallbackSnapshot: Snapshot?, stream: AsyncThrowingStream<Snapshot, any Error>?) {
            self.fallbackSnapshot = fallbackSnapshot
            self.streamIterator = stream?.makeAsyncIterator()
            self.useStream = stream != nil
        }

        public mutating func next() async throws -> Snapshot? {
            if useStream {
                if var iterator = streamIterator {
                    if let value = try await iterator.next() {
                        // store back the advanced iterator
                        streamIterator = iterator
                        return value
                    }
                    streamIterator = iterator
                }
                return nil
            } else {
                guard !hasYielded, let fallbackSnapshot else { return nil }
                hasYielded = true
                return fallbackSnapshot
            }
        }

        public typealias Element = Snapshot
    }

    public func makeAsyncIterator() -> AsyncIterator {
        return AsyncIterator(fallbackSnapshot: fallbackSnapshot, stream: streaming)
    }

    nonisolated public func collect() async throws -> sending LanguageModelSession.Response<Content> {
        if let streaming {
            var last: Snapshot?
            for try await snapshot in streaming {
                last = snapshot
            }
            if let last {
                // Attempt to materialize a concrete Content from the last snapshot
                let finalContent: Content
                if let concrete = last.content as? Content {
                    finalContent = concrete
                } else {
                    finalContent = try Content(last.rawContent)
                }
                return LanguageModelSession.Response(
                    content: finalContent,
                    rawContent: last.rawContent,
                    transcriptEntries: last.transcriptEntries,
                    usage: last.usage,
                    providerMetadata: last.providerMetadata
                )
            }
        }

        if let fallbackSnapshot {
            let finalContent: Content
            if let concrete = fallbackSnapshot.content as? Content {
                finalContent = concrete
            } else {
                finalContent = try Content(fallbackSnapshot.rawContent)
            }
            return LanguageModelSession.Response(
                content: finalContent,
                rawContent: fallbackSnapshot.rawContent,
                transcriptEntries: fallbackSnapshot.transcriptEntries,
                usage: fallbackSnapshot.usage,
                providerMetadata: fallbackSnapshot.providerMetadata
            )
        }

        throw ResponseStreamError.noSnapshots
    }
}

private enum ResponseStreamError: Error, LocalizedError {
    case noSnapshots

    var errorDescription: String? {
        switch self {
        case .noSnapshots:
            return "The response stream ended without producing a snapshot."
        }
    }
}

private struct ProfiledModelResponse<Content> where Content: Generable {
    let response: LanguageModelSession.Response<Content>
    let prepared: PreparedProfileRequest?
}

private struct ProfiledModelFailure: Error {
    let underlyingError: any Error
    let prepared: PreparedProfileRequest
}

fileprivate final class ProfileCallbackState: @unchecked Sendable {
    private let dispatchedEntryIDs = Locked<Set<String>>([])

    func wasDispatched(_ id: String) -> Bool {
        dispatchedEntryIDs.withLock { $0.contains(id) }
    }

    func markDispatched(_ id: String) {
        dispatchedEntryIDs.withLock { _ = $0.insert(id) }
    }
}

private final class PreparedProfileRequest: @unchecked Sendable {
    let session: LanguageModelSession
    let callSiteOptions: GenerationOptions
    private let state: Locked<State>

    init(
        session: LanguageModelSession,
        context: LanguageModelSession.RequestContext,
        callSiteOptions: GenerationOptions
    ) {
        self.session = session
        self.callSiteOptions = callSiteOptions
        state = Locked(State(context: context))
    }

    var context: LanguageModelSession.RequestContext {
        get { state.withLock { $0.context } }
        set { state.withLock { $0.context = newValue } }
    }

    private struct State: Sendable {
        var context: LanguageModelSession.RequestContext
    }
}

private final class PreparedProfileRequestTracker: @unchecked Sendable {
    private let storage = Locked<PreparedProfileRequest?>(nil)

    var prepared: PreparedProfileRequest? {
        get { storage.withLock { $0 } }
        set { storage.withLock { $0 = newValue } }
    }
}

private enum ProfileRequestBinding {
    @TaskLocal static var prepared: PreparedProfileRequest?
}

// MARK: -

private struct State: Equatable, Sendable {
    var transcript: Transcript
    var transcriptErrorHandlingPolicy: TranscriptErrorHandlingPolicy?
    var usage = LanguageModelSession.Usage.zero

    var isResponding: Bool { count > 0 }
    private var count = 0

    init(_ transcript: Transcript) {
        self.transcript = transcript
    }

    mutating func beginResponding() {
        count += 1
    }

    mutating func endResponding() {
        count = max(0, count - 1)
    }
}
